### ISSUE TITLE
test_protocol unittest failures on Windows

### ISSUE THREAD

**Issue by SzieberthAdam** [aaugustin/websockets#63] opened 2015-07-16 09:50 UTC
After fixing #62 there is still receive three failures. Note that these failures are identical for this repo and for my fork. Since these involving the protocol which I am not know enough yet to fix, I am dumping them to here.

Currently I am on my Linux environment:
4.0.7-2-ARCH
Python 3.4.3
64bit

If we got different failures here, I am here to help.

```python
[adam@sza8215 websockets]$ python -m unittest
...........Exception ignored in: Exception ignored in: Exception ignored in: Exception ignored in: Exception ignored in: Exception ignored in: /usr/lib/python3.4/asyncio/futures.py:151: ResourceWarning: unclosed <socket.socket fd=10, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 8642, 0, 0), raddr=('::1', 37256, 0, 0)>
  self._loop = events.get_event_loop()
/usr/lib/python3.4/asyncio/futures.py:151: ResourceWarning: unclosed <socket.socket fd=9, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 37256, 0, 0)>
  self._loop = events.get_event_loop()
/usr/lib/python3.4/asyncio/futures.py:151: ResourceWarning: unclosed <socket.socket fd=12, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 8642, 0, 0), raddr=('::1', 37257, 0, 0)>
  self._loop = events.get_event_loop()
/usr/lib/python3.4/asyncio/futures.py:151: ResourceWarning: unclosed <socket.socket fd=11, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 37257, 0, 0)>
  self._loop = events.get_event_loop()
/usr/lib/python3.4/asyncio/futures.py:151: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 8642, 0, 0), raddr=('::1', 37258, 0, 0)>
  self._loop = events.get_event_loop()
/usr/lib/python3.4/asyncio/futures.py:151: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 37258, 0, 0)>
  self._loop = events.get_event_loop()
....Exception ignored in: /usr/lib/python3.4/unittest/mock.py:1836: ResourceWarning: unclosed <socket.socket fd=15, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 37259, 0, 0), raddr=('::1', 8642, 0, 0)>
  self.name = name
...............Exception ignored in: Exception ignored in: /usr/lib/python3.4/_collections_abc.py:584: ResourceWarning: unclosed <ssl.SSLSocket fd=9, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 37276, 0, 0), raddr=('::1', 8642, 0, 0)>
  self, *args = args
/usr/lib/python3.4/_collections_abc.py:584: ResourceWarning: unclosed <ssl.SSLSocket fd=11, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 37277, 0, 0), raddr=('::1', 8642, 0, 0)>
  self, *args = args
....Exception ignored in: Exception ignored in: /usr/lib/python3.4/asyncio/base_events.py:437: ResourceWarning: unclosed <ssl.SSLSocket fd=12, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 37278, 0, 0), raddr=('::1', 8642, 0, 0)>
  handle = events.Handle(callback, args, self)
/usr/lib/python3.4/asyncio/base_events.py:437: ResourceWarning: unclosed <ssl.SSLSocket fd=9, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 37279, 0, 0), raddr=('::1', 8642, 0, 0)>
  handle = events.Handle(callback, args, self)
...Exception ignored in: Exception ignored in: /usr/lib/python3.4/threading.py:213: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 8642, 0, 0), raddr=('::1', 37259, 0, 0)>
  self._lock = lock
/usr/lib/python3.4/threading.py:213: ResourceWarning: unclosed <socket.socket fd=10, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 8642, 0, 0), raddr=('::1', 37266, 0, 0)>
  self._lock = lock
....Exception ignored in: /usr/lib/python3.4/selectors.py:396: ResourceWarning: unclosed <ssl.SSLSocket fd=10, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 8642, 0, 0), raddr=('::1', 37286, 0, 0)>
  key = super().register(fileobj, events, data)
..........................................F..........................................F.F...............................
======================================================================
FAIL: test_close_timeout_before_eof_received (websockets.test_protocol.ClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adam/github/notmy/websockets/websockets/test_protocol.py", line 480, in test_close_timeout_before_eof_received
    self.assertFalse(self.before.cancelled())
AssertionError: True is not false

======================================================================
FAIL: test_close_handshake_timeout (websockets.test_protocol.ServerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adam/github/notmy/websockets/websockets/test_protocol.py", line 360, in test_close_handshake_timeout
    self.assertFalse(self.before.cancelled())
AssertionError: True is not false

======================================================================
FAIL: test_close_timeout_before_connection_lost (websockets.test_protocol.ServerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adam/github/notmy/websockets/websockets/test_protocol.py", line 376, in test_close_timeout_before_connection_lost
    self.assertFalse(self.before.cancelled())
AssertionError: True is not false

----------------------------------------------------------------------
Ran 160 tests in 4.876s

FAILED (failures=3)
```

**Comment by aaugustin** [comment] 2015-07-16 18:37
Great, thanks for reporting these. I also noticed some failures when running tests under tox. (I'm not sure why this makes a difference.)

I'm a bit busy today, I'll try to follow up as soon as possible.

**Comment by SzieberthAdam** [comment] 2015-07-20 20:26
The ailures above were produced by my work environment, an old IBM Thinkcentre with 2.8 Ghz Celeron CPU. Current lines are 488, 366, and 382. This PC produces the failures above constantly.

However, I was also tested it with my (also old) MSI laptop (AMD Athlon 64 X2 Dual-Core TK-57) which produces inconsistent results.

**Comment by SzieberthAdam** [comment] 2015-07-20 20:59
Now I noticed I do testing while the repo is acively changing. I get back later.

**Comment by aaugustin** [comment] 2015-07-20 21:03
Yes, I just pushed a bunch of changes I've been working on yesterday and today. (I have limited Internet connectivity.)

I can reproduce `test_close_timeout_before_connection_lost` reliably. I'm going to look into it. I haven't seen other failures regularly.

If you're running the tests on a slow machine, try increasing the value of `MS` in `websockets/test_protocol.py` and see if that helps.

**Comment by aaugustin** [comment] 2015-07-20 21:55
I took a closer look at your report. There are several issues.

1. `ClientTests.test_close_timeout_before_connection_lost` was buggy. I've just pushed a fix.
2. Failures on `self.assertFalse(self.before.cancelled())` are probably explained by the difference between your hardware / OS and mine. These tests check that timeouts are applied correctly by asserting that some coroutines complete in a given time. Like I said above, changing `MS` should make them pass. I'd like to keep `MS` set to 1 millisecond by default because that makes the tests run very fast :-) However I could allow overriding it with an environment variable for convenience (and if I ever want to run these tests on some cloud CI service).
3. `ClientTests.test_client_close` could be a different syndrom of the same cause root cause. It looks like the coroutine scheduled at 3ms runs before the sequence of actions triggered at 1ms completes.

Would you mind pulling the latest commit to master, setting `MS = 0.01` in `websockets/test_protocol.py` and letting me know if you still see any failures? (If you have tox installed, you can simply run `tox`.)

**Comment by SzieberthAdam** [comment] 2015-07-21 04:01
Sure, I'll do that today afternoon/evening.

**Comment by SzieberthAdam** [comment] 2015-07-22 07:26
Done. Conclusions:

1. Yep, the remaining failure is produced by lines 505-506, mostly 505. However, when I set the MS lower (0.0005) then line 506 produces the failure. Are not the two rows somehow in the opposite order? Increasing MS even with insane amount does not solve it.

2. `test_close_timeout_before_eof_received()`, `test_close_handshake_timeout()`, and `test_close_timeout_before_connection_lost()` all fail at `assertFalse()`. By setting MS to 0.003 they pass even on my slowest PC. The time of the testing increases by 0.15 s after the global MS adjustment. What I would do is to adjust the delays in these particular tests a bit. I will do that gladly if you agree Aymeric. I usually like to develop on old PCs. Easier to recognise bad code by noticing slowness.

3. Yes, for some reason, `test_client_close()` works the same like (1.), although it passes at the end. At MS=0.0001 it failes at line 460, at MS=0.0005 it fails at line 458. However, at MS=0.001 it passes (on my laptop/ARCH; the Thinkcentre needs MS=0.002 to not fail at 458).

**Comment by aaugustin** [comment] 2015-07-23 18:37
Thanks for the feedback.

I just had an idea to make the tests both fast and robust: instead of using `self.loop.call_later(X * MS, do_stuff)` with incremental values of `X`, I can just use `self.loop.call_soon(do_stuff)`. `asyncio` guarantees that functions scheduled with `call_soon` are executed in order.

I'm working on a patch. Not only does this makes the tests look much nicer, but they should also be more deterministic and faster. Then I can increase the value of MS when I test timeouts without making the whole test suite proportionally slower.

Let's see where we stand once I've completed this refactoring!

**Comment by SzieberthAdam** [comment] 2015-07-23 21:59
Good idea! I wasn't aware of this benefit of `call_soon()` until now.

**Comment by aaugustin** [comment] 2015-07-26 21:42
I just pushed a series of commits that should improve the situation significantly.

Feel free to test again and report your findings at your convenience. Thanks!

**Comment by aaugustin** [comment] 2015-07-27 11:56
Tentatively closing as fixed.

**Comment by SzieberthAdam** [comment] 2015-07-27 19:03
At commit 9bdfb81780f71eac09dd154a75a09e9dbe03b81e on my Windows environment:
```
adam@SZAMSI E:\websockets
> python -m unittest
...........................................................................................................F.....F........................F.......F.....F.................................
======================================================================
FAIL: test_close_handshake_timeout (websockets.test_protocol.ClientCloseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\websockets\websockets\test_protocol.py", line 581, in test_close_handshake_timeout
    self.loop.run_until_complete(self.protocol.close(reason='close'))
  File "C:\Python34\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "E:\websockets\websockets\test_protocol.py", line 167, in assertCompletesWithin
    dt, min_time, "Too fast: {} < {}".format(dt, min_time))
AssertionError: 0.01599999999962165 not greater than or equal to 0.019 : Too fast: 0.01599999999962165 < 0.019

======================================================================
FAIL: test_eof_received_timeout (websockets.test_protocol.ClientCloseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\websockets\websockets\test_protocol.py", line 593, in test_eof_received_timeout
    self.loop.run_until_complete(self.protocol.close(reason='close'))
  File "C:\Python34\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "E:\websockets\websockets\test_protocol.py", line 167, in assertCompletesWithin
    dt, min_time, "Too fast: {} < {}".format(dt, min_time))
AssertionError: 0.0 not greater than or equal to 0.009000000000000001 : Too fast: 0.0 < 0.009000000000000001

======================================================================
FAIL: test_server_close_race_with_failing_connection (websockets.test_protocol.ClientCloseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\websockets\websockets\test_protocol.py", line 609, in test_server_close_race_with_failing_connection
    self.assertOneFrameSent(*self.server_close)
  File "E:\websockets\websockets\test_protocol.py", line 147, in assertOneFrameSent
    self.assertEqual(self.last_sent_frame(), Frame(fin, opcode, data))
AssertionError: Frame(fin=True, opcode=8, data=b'\x03\xe8client') != Frame(fin=True, opcode=8, data=b'\x03\xe8server')

======================================================================
FAIL: test_client_close_race_with_failing_connection (websockets.test_protocol.ServerCloseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\websockets\websockets\test_protocol.py", line 473, in test_client_close_race_with_failing_connection
    self.assertOneFrameSent(*self.client_close)
  File "E:\websockets\websockets\test_protocol.py", line 147, in assertOneFrameSent
    self.assertEqual(self.last_sent_frame(), Frame(fin, opcode, data))
AssertionError: Frame(fin=True, opcode=8, data=b'\x03\xe8server') != Frame(fin=True, opcode=8, data=b'\x03\xe8client')

======================================================================
FAIL: test_close_handshake_timeout (websockets.test_protocol.ServerCloseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\websockets\websockets\test_protocol.py", line 458, in test_close_handshake_timeout
    self.loop.run_until_complete(self.protocol.close(reason='close'))
  File "C:\Python34\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "E:\websockets\websockets\test_protocol.py", line 167, in assertCompletesWithin
    dt, min_time, "Too fast: {} < {}".format(dt, min_time))
AssertionError: 0.0 not greater than or equal to 0.009000000000000001 : Too fast: 0.0 < 0.009000000000000001

----------------------------------------------------------------------
Ran 186 tests in 3.962s

FAILED (failures=5)
```

**Comment by aaugustin** [comment] 2015-07-28 21:23
The second set of failures is clearly caused by the old Thinkcentre being a bit slow. With `WEBSOCKETS_TESTS_TIMEOUT_FACTOR=2 python -m unittest` the tests should pass. Fewer tests depend on fixed timeouts now, so I could increase their duration without harming the test suite's overall run time.

**Comment by aaugustin** [comment] 2015-07-28 21:24
I would need access to a Windows machine to reproduce your first set of failures. Two causes come to mind:

- the clock used by asyncio on Windows not having a very good resolution
- IOCP (overlapped I/O) doing smart things I do not expect

**Comment by SzieberthAdam** [comment] 2015-07-30 11:36
Confirmed working with `WEBSOCKETS_TESTS_TIMEOUT_FACTOR=2` environment variable on slow PC.

**Comment by aaugustin** [comment] 2015-08-08 10:59
asyncio's clock relies on `time.monotonic()`. It is implemented with GetTickCount on Windows which has ~16ms resolution. That's why some tests fail with timings rounded to 0ms or 16ms.

**Comment by aaugustin** [comment] 2015-08-08 11:02
With the commit I just pushed, I don't see failures on Windows anymore.

**Closed** 2015-08-08 11:01 UTC

**Comment by SzieberthAdam** [comment] 2015-08-15 07:11
Confirmed fixed.

**Comment by aaugustin** [comment] 2015-08-15 07:48
Success \o/ Thanks!
