### ISSUE TITLE
websocket.recv() creating problem 

### ISSUE THREAD

**Issue by pranaysingh25** [aaugustin/websockets#909] opened 2021-02-20 13:29 UTC
Hi, 

I am using websockets for receiving messages from a client which also uses websockets. My server which is hosting the connection is waiting for the message using websocket.recv(), this is the first anticipated message in my use case, for eg; "Start" . 
After doing some operations below the receive command, I have put another websocket.recv() down there which waits for another message and then I do some other set of operations below it after receiving that command, for eg: "Stop".

What happens is, after receiving the 1st message that the client sends, the control of the program waits on the second recv() command as if its waiting for any message again, which is understandable since the command is blocking. but what's not understandable is the moment 2nd message is sent by the client there, the program control here goes to the 1st line of the function, and eventually the message is received by top most recv() command. which received the 1st message. I don't understand why the control has to go back all the way to the first line ditching the second recv() command on which it was waiting. I eventually get my message 2nd time as well but not from where I had expected it(2nd recv() command) and program comes down executing all the above statements again.
Isn't there a way I can receive my messages where ever I want in my code ? or there something I am missing ? I am putting down a snippet of code, Requesting to look into the concern.

```
async def foo(websocket, path):
// this is the 1st of the function foo
    message_1 = await websocket.recv()  # this is 1st recv() command
    // do something with the message

    message_2 = await websocket.recv()  # this is 2nd recv() command
    // do something with the message 

websocket_server = websockets.serve(foo, host, port)
asyncio.get_event_loop().run_until_complete(websocket_server)
asyncio.get_event_loop().run_forever() 
```

Thank You!

**Comment by aaugustin** [comment] 2021-02-21 07:21
Indeed this is very unexpected. With the information you provided, I'm not able to reproduce.

Could you provide a minimal reproduction of this problem = a complete client script and a complete server script?

**Comment by aaugustin** [comment] 2021-05-01 21:01
Closing because I don't have enough information to reproduce. There's a high chance you got your logic wrong.

**Closed by aaugustin** 2021-05-01 21:01 UTC
