### ISSUE TITLE
Unable to recv() from connection in v10

### ISSUE THREAD

**Issue by sigvardsen** [aaugustin/websockets#1057] opened 2021-09-26 09:43 UTC
Hi, 

When using websockets 10, the following connection will never return `recv()`, whereas it works fine in 9.1

```import websockets
import logging
logger = logging.getLogger('websockets')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())
async with websockets.connect("wss://fstream.binance.com:443/ws/stream/") as websocket:
        await websocket.send('{"method": "SUBSCRIBE", "id": 0, "params": ["btcusdt@aggTrade"]}')
        while True:
                print(await websocket.recv())

**Comment by aaugustin** [comment] 2021-09-26 13:21
This looks very similar to #1050. Closing as a duplicate for now. Let's reopen if you find cues suggesting that it's a different case or that websockets is the culprit. I'm pretty sure the problem is on the server side though.

**Closed by aaugustin** 2021-09-26 13:21 UTC

**Comment by aaugustin** [comment] 2021-09-26 13:26
A 5 minutes investigation shows exactly the same symptoms, so I suspect binance and bitpanda use the same software and suffer the same bugs.
