### ISSUE TITLE
Any idea what might cause "Cannot call write() after write_eof()"?

### ISSUE THREAD

**Issue by jacksonofalltrades** [aaugustin/websockets#320] opened 2017-12-11 03:29 UTC
Traceback (most recent call last):
  File "/srv/locix/locix/websocket/server.py", line 184, in ping_handler
    await websocket.ping()
  File "/usr/local/lib/python3.5/dist-packages/websockets/protocol.py", line 433, in ping
    yield from self.write_frame(OP_PING, data)
  File "/usr/local/lib/python3.5/dist-packages/websockets/protocol.py", line 654, in write_frame
    extensions=self.extensions,
  File "/usr/local/lib/python3.5/dist-packages/websockets/framing.py", line 210, in write
    writer(output.getvalue())
  File "/usr/lib/python3.5/asyncio/streams.py", line 294, in write
    self._transport.write(data)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 687, in write
    raise RuntimeError('Cannot call write() after write_eof()')

**Comment by aaugustin** [comment] 2017-12-11 20:49
Hrm, that's weird, you should be getting an exception such as "InvalidState: Cannot write to a websocket in the CLOSED state" if websockets somehow tries to write a frame after (or while) terminating the connection.

**Comment by jacksonofalltrades** [comment] 2017-12-12 05:32
So this seems pretty clearly to be because the socket was closed before the ping call was made? Hm, ok.

**Comment by cjerdonek** [comment] 2017-12-12 09:17
Maybe this is because in `WebSocketCommonProtocol.close_connection()`, there is a `yield from self.wait_for_connection_lost()` after `self.writer.write_eof()` is called and before `self.writer.close()` (which changes `self.state`) is called: https://github.com/aaugustin/websockets/blob/136d9bc9a917f7f5fdde4001e801b591ee1b4a0b/websockets/protocol.py#L724-L741

**Comment by aaugustin** [comment] 2017-12-12 09:50
https://github.com/aaugustin/websockets/blob/136d9bc9a917f7f5fdde4001e801b591ee1b4a0b/websockets/protocol.py#L640-L655 doesn't yield between the check that the connection state is OPEN and the write which cause this exception.

This means we're calling `write_eof` while the connection state is still OPEN, which is wrong.

@jacksonofalltrades If the exception is easily reproducible, could you try adding a `print websocket.state` just before `await websocket.ping()` so we can confirm the connection state here?

Unfortunately the RFC doesn't cover error cases when it describes connection state handling. If memory serves, it says that the connection moves to the CLOSING state when a Close frame is received or sent and to the CLOSED state when the TCP connection is closed.

So what should the state be when the connection receives a TCP half-close from the remote side?No Close frame is involved so the state cannot be CLOSING. The TCP connection isn't closed yet so the state cannot be CLOSED.

We may need to add another flag to the WebSocketProtocol classes to say: "we're in an error situation, closing the TCP connection without a proper handshake, don't try to send frames".

These are the situations that end with a 1006 status code. There are hardcoded checks with this error code that could be handled more elegantly with such a flag: https://github.com/aaugustin/websockets/blob/136d9bc9a917f7f5fdde4001e801b591ee1b4a0b/websockets/protocol.py#L786-L789

**Comment by cjerdonek** [comment] 2017-12-12 09:58
> This means we're calling write_eof while the connection state is still OPEN, which is wrong.

Would it be worth adding an assertion to detect this case?

**Comment by jacksonofalltrades** [comment] 2017-12-12 14:34
Sure, I can add that. I'll let you know what happens.

**Comment by jacksonofalltrades** [comment] 2017-12-12 19:08
State is OPEN when this happens. That seems especially odd.

**Comment by cjerdonek** [comment] 2017-12-12 19:46
What is causing `write_eof()` to be called? Is it `close_connection()` linked in my comment above? If so, what is causing that to be awaited?

**Comment by jacksonofalltrades** [comment] 2017-12-12 23:18
@cjerdonek I wish I could tell you. I've put some logging into the `/usr/lib/python3.5/asyncio/selector_events.py` write_eof function, but I'm not seeing any that happen around the same time as the exception on websocket.ping.

**Comment by jacksonofalltrades** [comment] 2017-12-13 03:13
I've added logging to print the traceback in write_eof so I can see what called it when it happens near the exception in this ticket. I'm seeing the traceback is "NoneType." How can there be no traceback when write_eof is called? Something must have called it.

**Comment by jacksonofalltrades** [comment] 2017-12-13 03:14
Any advice on what to log here?

**Comment by cjerdonek** [comment] 2017-12-13 09:15
What does your logging code look like? Are you passing `stack_info=True`?
https://docs.python.org/3/library/logging.html#logging.Logger.debug

**Comment by jacksonofalltrades** [comment] 2017-12-13 18:05
I'm wondering if my ping interval is too long and this problem is caused by the time since last ping having caused the connection to start closing on the client, without the server knowing yet. Is there any standard on how long browsers wait for a ping/keepalive before timing out a tcp / websocket connection? I've tried to do some searching but not finding anything on that. Thanks!

**Comment by aaugustin** [comment] 2017-12-13 21:28
I'd use 30 seconds as the ping interval. TCP timeout is variable, I'd bet on 2 minutes in usual situations.

I don't have official sources to back these figures.

**Comment by jacksonofalltrades** [comment] 2017-12-13 23:22
I'm also still unable to figure out why after a time my websocket server fails to reply to health checks quickly enough. I mention it here only because I wonder if it's related to the error in my initial post here using up cycles. AWS has not made debugging health check failures easy.

**Comment by jacksonofalltrades** [comment] 2017-12-13 23:24
I've reduced my ping interval to 10 seconds and this is still happening with quite high frequency (the write_eof thing). It does seem to happen more, the more clients I have connected to the server.

**Comment by cjerdonek** [comment] 2017-12-14 00:18
Did you see my comment? https://github.com/aaugustin/websockets/issues/320#issuecomment-351330488

**Comment by jacksonofalltrades** [comment] 2017-12-14 00:26
@cjerdonek Yes, the problem is I've been manually adding logging to the asyncio library itself to try to capture what's calling write_eof and my changes keep getting wiped when the server restarts. I've been just using `import traceback` and traceback.format_exc() in my logger call. I haven't tried stack_info=True.

**Comment by aaugustin** [comment] 2018-05-17 21:02
OK, I just understood what @cjerdonek meant in this comment: https://github.com/aaugustin/websockets/issues/320#issuecomment-350991704

We're only relying on `self.state` for tracking the connection state. Unfortunately this isn't sufficiently accurate around state transitions.

There's a gap of time between the moment the connection becomes unusable in `close_connection` and the moment it's fully closed. Control yields to the event loop several times. The connection state remains OPEN all the while if there was no closing handshake.

(I was working on a similar situation a few minutes ago. `write_close_frame` sets the state to CLOSING before sending a Close frame in order to ensure that at most one close frame is sent, while the spec says that the state should be changed to CLOSING after receiving or sending a close frame. We're bending the spec slightly there to avoid such a gap.)

Perhaps we can improve the implementation of ensure_open() to fix this issue, for example by checking that `transfer_data_task` is still running. It must be done before reaching the point where where `close_connection` calls `self.writer.write_eof()`.

**Comment by aaugustin** [comment] 2018-05-19 07:05
This PR isn't particularly elegant (especially the test strongly coupled with the implementation) but I think it gets the job done without adding more state to the protocol class.

**Closed** 2018-05-19 08:27 UTC
Labels: bug, has patch
