### ISSUE TITLE
How would I modify my code to auto-ping every 2s, to avoid disconnects

### ISSUE THREAD

**Issue by vgoklani** [aaugustin/websockets#446] opened 2018-07-24 21:18 UTC
Hello - here is my code that connects to a websocket:

	async def connect(self):
		while True:
			log.info("connecting")
			async with websockets.connect(self.url, max_queue=4 * 2**10,) as websocket:
				log.info("connected")
				await websocket.send(json.dumps(self.subscribe))
				log.info("subscribed: {}".format(websocket.remote_address))
				while(True):
					try:
						message_str = await asyncio.wait_for(websocket.recv(), timeout=self._timeout)
						self.queue.put_nowait(message_str)
					except asyncio.TimeoutError:
						log.warn("timeout error - no data in {} seconds, pinging connection".format(self._timeout))
						pong_waiter = await asyncio.wait_for(websocket.ping("keepalive"), timeout=self._timeout)
						await asyncio.wait_for(pong_waiter, timeout=2 * self._timeout)
						log.warn('ping/pong received, keeping connection alive...')
					except Exception as e:
						error_message = "resetting connection: {}".format(e.args)
						log.error(error_message)
						raise Exception(error_message)

How would I modify this to auto-ping every 2s?

I think it would need to be a task in a separate loop(?) so as to not block the websocket.recv()?

**Comment by aaugustin** [comment] 2018-07-29 09:15
The task must run in the same loop. Reading about "cooperative multitasking" may help you.

When #383 is implemented, it will provide an example of how to do this.

**Comment by aaugustin** [comment] 2018-07-29 16:09
Closing as a duplicate of #383, which now has a proposed implementation in #449. Please follow-up in these issues.

**Closed by aaugustin** 2018-07-29 16:09 UTC
