### ISSUE TITLE
Deprecation of loops shouldn't break test suite on 3.8

### ISSUE THREAD

**Issue by mcepl** [aaugustin/websockets#1081] opened 2021-10-29 13:11 UTC
When packaging 10.0 for openSUSE I got 183 failures in the test suite (yes :(). Many of them are like this (just picked one random):
```
[   52s] ======================================================================
[   52s] FAIL: test_server_create_protocol (tests.legacy.test_client_server.ClientServerTests)
[   52s] ----------------------------------------------------------------------
[   52s] Traceback (most recent call last):
[   52s]   File "/home/abuild/rpmbuild/BUILD/websockets-10.0/tests/legacy/test_client_server.py", line 126, in _decorate
[   52s]     with manager(self, *args, **kwargs):
[   52s]   File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
[   52s]     return next(self.gen)
[   52s]   File "/home/abuild/rpmbuild/BUILD/websockets-10.0/tests/legacy/test_client_server.py", line 96, in temp_test_server
[   52s]     test.start_server(**kwargs)
[   52s]   File "/home/abuild/rpmbuild/BUILD/websockets-10.0/tests/legacy/test_client_server.py", line 232, in start_server
[   52s]     self.assertDeprecationWarnings(recorded_warnings, expected_warnings)
[   52s]   File "/home/abuild/rpmbuild/BUILD/websockets-10.0/tests/legacy/utils.py", line 79, in assertDeprecationWarnings
[   52s]     self.assertEqual(
[   52s] AssertionError: Items in the first set but not the second:
[   52s] 'The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.'
[   52s]
```

[Full log of the build](https://github.com/aaugustin/websockets/files/7442128/_log.txt) with all details on packages used and steps taken to achieve it.

It seems to me that in your understandable effort to deprecate old command you broke your whole test suite. Any ideas how to fix it?

**Comment by aaugustin** [comment] 2021-10-30 05:40
It seems to me that you jumped to the conclusion that I was dumb enough to break my own test suite a bit too fast :-)

This is a bug in Python 3.9.7. It doesn't affect websockets itself; it only causes the test suite to fail. Duplicate of #1051.

**Closed by aaugustin** 2021-10-30 05:40 UTC
