### ISSUE TITLE
How to get request headers on Server to Process them.

### ISSUE THREAD

**Issue by ajajchauhan** [aaugustin/websockets#491] opened 2018-10-23 15:21 UTC
I am trying to create a application with Python and WebSocket. Web browsers will connect to the server and also the Headers will contain some cookies. How can I get and process them.

Code that I am using is as follows :
```
import asyncio
import websockets

async def hello(websocket, path):
    name = await websocket.recv()
    print(f"< {name}")

    greeting = f"Hello {name}!"

    await websocket.send(greeting)
    print(f"> {greeting}")
    print(websocket.extra_headers)

start_server = websockets.serve(hello, 'localhost', 8765)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

How will I get the Headers (cookies).
Please help.

**Comment by aaugustin** [comment] 2018-10-25 13:58
They're in `websocket.request_headers`.

The documentation mentions it but it isn't as easy to find as it should be.

**Comment by ajajchauhan** [comment] 2018-10-26 18:01
Thanks for the reply.

**Comment by aaugustin** [comment] 2019-06-24 05:49
Closing as a duplicate of #621.

**Closed by aaugustin** 2019-06-24 05:49 UTC
Labels: documentation
