### ISSUE TITLE
Crash when using Python 3.7 - runs fine in Python 3.6

### ISSUE THREAD

**Issue by MrYsLab** [aaugustin/websockets#433] opened 2018-07-05 18:08 UTC
I am running the following program:
https://github.com/MrYsLab/pymata-aio/blob/master/pymata_aio/pymata_iot.py

In Python 3.7, I get the following exception traceback
```
Traceback (most recent call last):
  File "/home/afy/PycharmProjects/pymata-aio/pymata_aio/pymata_iot.py", line 716, in <module>
    asyncio.get_event_loop().run_until_complete(start_server)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 599, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/usr/local/lib/python3.7/site-packages/websockets/server.py", line 742, in __await__
    server = yield from self._creating_server
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
sys:1: RuntimeWarning: coroutine 'BaseEventLoop.create_server' was never awaited```

```
Here is the section of my code generating the error:
```
try:
    start_server = websockets.serve(server.get_message, '127.0.0.1', 9000)

    asyncio.get_event_loop().run_until_complete(start_server)

    asyncio.get_event_loop().run_forever()
except websockets.exceptions.ConnectionClosed:
    sys.exit()
except RuntimeError:
    sys.exit()

```
Line 716 is: 
```
asyncio.get_event_loop().run_until_complete(start_server)
```

**Comment by RemiCardona** [comment] 2018-07-05 19:07
Python 3.7 is supported only on git master. The next release will include the necessary code. Closing as a dupe of #405.

Thanks

**Closed by RemiCardona** 2018-07-05 19:07 UTC

**Comment by aaugustin** [comment] 2018-07-16 19:56
Version 6.0 adds support for Python 3.7 and is now available on PyPI: https://pypi.org/project/websockets/6.0/#files
