### ISSUE TITLE
Access the "local" close code in addition to the "remote" close code provided in ConnectionClosed

### ISSUE THREAD

**Issue by higleyc** [aaugustin/websockets#587] opened 2019-03-20 13:16 UTC
Hi, thanks for your work on this project aaugustin and all!

I'd like to be able to catch the reason for a connection-close server side - particularly if it's a 1009. While this code is being correctly returned to the client when messages exceed the max size, the exception raised server-side seems to always have 1006. Simple example:

```
async def hello(websocket, path):
    try:
        await websocket.recv()
    except websockets.exceptions.ConnectionClosed as e:
        traceback.print_exc()
        print(f">>>>>> caught code is {e.code}")

start_server = websockets.serve(hello, 'localhost', 8765, max_size=1024)
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

The output is:
```
asyncio - DEBUG - Using selector: EpollSelector
websockets.protocol - DEBUG - server - state = CONNECTING
websockets.protocol - DEBUG - server - event = connection_made(<_SelectorSocketTransport fd=8 read=idle write=<idle, bufsize=0>>)
websockets.protocol - DEBUG - server - state = OPEN
websockets.protocol - DEBUG - server ! failing WebSocket connection in the OPEN state: 1009 [no reason]
websockets.protocol - DEBUG - server - state = CLOSING
websockets.protocol - DEBUG - server > Frame(fin=True, opcode=8, data=b'\x03\xf1', rsv1=False, rsv2=False, rsv3=False)
websockets.protocol - DEBUG - server x half-closing TCP connection
websockets.protocol - DEBUG - server - event = eof_received()
websockets.protocol - DEBUG - server - event = connection_lost(None)
websockets.protocol - DEBUG - server - state = CLOSED
websockets.protocol - DEBUG - server x code = 1006, reason = [no reason]
Traceback (most recent call last):
  File "/home/hu/rand/wsclose/env/lib/python3.6/site-packages/websockets/protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "/home/hu/rand/wsclose/env/lib/python3.6/site-packages/websockets/protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/home/hu/rand/wsclose/env/lib/python3.6/site-packages/websockets/protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/home/hu/rand/wsclose/env/lib/python3.6/site-packages/websockets/protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "/home/hu/rand/wsclose/env/lib/python3.6/site-packages/websockets/framing.py", line 138, in read
    frame = extension.decode(frame, max_size=max_size)
  File "/home/hu/rand/wsclose/env/lib/python3.6/site-packages/websockets/extensions/permessage_deflate.py", line 522, in decode
    max_size
websockets.exceptions.PayloadTooBig: Uncompressed payload length exceeds size limit (? > 1024 bytes)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "wsclose.py", line 9, in hello
    await websocket.recv()
  File "/home/hu/rand/wsclose/env/lib/python3.6/site-packages/websockets/protocol.py", line 434, in recv
    yield from self.ensure_open()
  File "/home/hu/rand/wsclose/env/lib/python3.6/site-packages/websockets/protocol.py", line 658, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
>>>>>> caught code is 1006
```

So apparently the `PayloadTooBig` is being translated into a `ConnectionClosed` with 1006 which seems to be the default code. My naive analysis: should we just be storing the code in `fail_connection()` in `self.close_code`?

**Comment by aaugustin** [comment] 2019-03-20 15:15
Two logical decisions end up producing an annoying result here.

1) The WebSocket connection close code is the value _received from the remote endpoint in a close frame_ (the client in your situation) — not the value sent in a close frame.

Here websockets is failing the connection i.e. sending a close frame and terminating the connection without waiting for a response. So you never receive a close frame and the connection close code is 1006.

This might not be what you expect but [the spec is unambiguous](https://tools.ietf.org/html/rfc6455#section-7.1.5).

2) websockets waits until there's the connection close code is known to raise a ConnectionClosed exception with the correct code — so you don't get different close codes depending on subtle timing differences.

This is why you get a 1006, the eventual close code for that connection.

----

Thanks to exception chaining you're seeing clearly what's happening in the stack trace. However, it's a bit difficult to tell what happened programatically. The issue is valid. I'm not sure but what the best solution is.

**Comment by higleyc** [comment] 2019-03-20 15:41
I understand now. I can simply check `isinstance(e.__cause__, websockets.exceptions.PayloadTooBig)` to get the context I'm looking for. This behavior seems completely reasonable to me per your comments about the RFC.

Thanks for the help!

**Comment by aaugustin** [comment] 2019-03-20 16:16
I'd like to keep the issue open because this deservers a less hacky API.

**Comment by aaugustin** [comment] 2021-05-02 20:47
#877 contains a good discussion with some details.

**Comment by cjerdonek** [comment] 2021-06-03 22:23
On this issue (continuing my thoughts from #877), does the spec actually weigh in on how errors should be reported to _developers_? (The spec does recognize developers as an entity, as it mentions them [here](https://datatracker.ietf.org/doc/html/rfc6455#section-7.1.7).) More specifically, does the spec actually require that the code reported to developers be ["The WebSocket Connection Close Code"](https://datatracker.ietf.org/doc/html/rfc6455#section-7.1.5) (in the sense of the spec), if a different code would be more useful?

In the case of an endpoint initiating a closure, it seems like the close code _sent_ by the endpoint is more likely to contain useful information, since that will always be something other than 1006. So if you're limited to reporting just one to developers, it seems like that one should be preferred.

Either way, it seems like you couldn't go wrong by modifying `ConnectionClosedError` to store both codes and reasons (i.e. both the one sent _and_ received), as I suggested at the end of [my comment here](https://github.com/aaugustin/websockets/issues/877#issuecomment-752766044). In addition, I think it would be helpful to have a property that surfaces a single code, which would be the one containing more information (e.g. if an endpoint initiated a closure with a certain code but didn't receive a code back, it should prefer the former, as that is the one containing more information).

**Comment by cjerdonek** [comment] 2021-06-03 23:07
Also, for the above, it might be useful to define a `CloseInformation` object that encapsulates all three of (1) a close code, (2) a close reason, and (3) either "this endpoint" or "other endpoint." That way, if `ConnectionClosedError` is to surface a single cause for the error (e.g. PayloadTooBig) as I suggested in my previous comment, the object will also include the information of which endpoint that info is associated with.

**Comment by aaugustin** [comment] 2021-06-04 08:10
I was thinking of keeping things super simple: the "local" close code and reason as attributes of the protocol and the ConnectionClosed exception.

The end result could look like:

```
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: received code = 1006 (connection closed abnormally [internal]), no reason; sent code = 1009 (payload too big), no reason
```

**Comment by cjerdonek** [comment] 2021-06-04 08:17
It seems like another useful piece of info would be which happened first -- the sending or receiving, as that would give a clearer indicator of the initiator of the close.

**Comment by aaugustin** [comment] 2021-06-05 16:38
I agree that it could be useful to record who initiated the closing handshake. Note that, due to network delays and/or buffering, it is possible to end up in a situation where both sides think they initiated the closing handshake.

Barring bugs in websockets we have the following scenarios:

1. connection closed with a standard closing handshake
    * close frames sent and received with the same code and reason, regardless of which side initiated the handshake — this is the standard case; my proposal would duplicate the info which isn't great
2. connection closed with a race condition in the closing handshake
    * close frames sent and received with the same code and reason
    * close frames sent and received with different code and reason
3. connection closed without a proper closing handshake
    * close frame sent, no close frame received — this is the most common cause of complaints
    * close frame received, no close frame sent — this may happen if the incoming close frame sits in buffers, the TCP connection drops, and then the incoming close frame is processed
    * no close frame sent or received — not much to display here!

I'd like to think about what we want to display to the developer in each case. Then we can see the best data model.

**Option A**

- list of 0, 1, or 2 elements containing side/code/reason

**Option B**

- local code/reason
- remote code/reason
- which side shot first

**Comment by cjerdonek** [comment] 2021-06-05 23:48
> I'd like to think about what we want to display to the developer in each case.

Here are some initial thoughts. For starters, I think it would be good if the string display was in the order the events happened, so it could be read loosely as "this happened first, then that happened."

As far as "no close frame received" and "no close frame sent," there is the question of whether each should be included in the display or omitted, and if they are displayed, should "no close frame received" show up as "no close frame received" or "received close code 1006"? Maybe best would be if the display always shows something for received and sent, whether or not something was received or sent. That way there isn't any ambiguity as to what happened. As for, say, "receiving 1006," maybe the display could somehow indicate not just that it's the receiving side but also that nothing was actually received. For example, something like the following.

For sent and received:

```
<ConnectionClosed received: 1009 (Unsupported Data), then sent: 1009 (Unsupported Data)> 
```

Notice the word "then" to indicate that the ordering is meaningful.

For sent and nothing received:

```
<ConnectionClosed: sent 1009 (Message Too Big), nothing received: 1006 (Abnormal Closure)> 
```

Here "then" is omitted because it's not needed when something didn't happen.

**Comment by cjerdonek** [comment] 2021-06-06 00:00
To add one more thing: for the "receiving" side, it's like there is one more bit of information in addition to the close code and reason, namely "was this code received by the client" (as opposed to a stand-in code generated by the application). So it would be good if the display could reflect this distinction.

**Comment by aaugustin** [comment] 2021-06-14 20:48
I believe the proposal below covers all use cases.

Thanks @cjerdonek for pointing out that the order matters. Indeed, even for a proper closing handshake, it's useful to know which side triggered it.

1. close frames sent and received with the same code and reason

    `received 1000 (OK) Bye! after sending 1000 (OK) Bye!`
    `received 1001 (going away) then sent 1001 (going away)`

    In the first example Bye! is the close reason. I won't include it in other examples but it could always be there.

2. close frames sent and received with a different code and reason (same implementation as 1 actually)

    `received 1002 (protocol error) after sending 1008 (policy violation)`
    `received 1001 (going away) then sent 1002 (protocol error)`

3. close frame sent, no close frame received

    `no close frame received; sent 1009 (payload too big)`

4. close frame received, no close frame sent

    `received 1002 (protocol error); no close frame sent`

5. no close frame sent or received

    `no close frame received; no close frame sent`

Regarding internal codes:

- `1006` is translated to `no close frame received` — this is a special case.
- `1005` will show up as `1005 (no status code [internal])` — this doesn't happen in practice because all WebSocket implementations manage to create valid close frames.
- `1015` isn't generated by websockets but, if it were, it would show up as `1015 (TLS failure [internal])`.

**Comment by aaugustin** [comment] 2021-06-16 21:17
#998 is almost done - just needs a bit more docs. Comments welcome!

Look in `src/websockets/exceptions.py` for the exact wording I settled on.

@cjerdonek Stand-in codes are indicated by `[internal]`. Furthermore, the only stand-in code that occurs in practice is 1006 and I'm translating it to "no close frame sent / received" so I think we're good.

**Comment by cjerdonek** [comment] 2021-06-17 02:12
> #998 is almost done - just needs a bit more docs. Comments welcome!

I will comment there, but at first glance, all looks great!

**Closed** 2021-06-17 05:37 UTC
Labels: enhancement, high priority
