### ISSUE TITLE
client always times out

### ISSUE THREAD

**Issue by SzieberthAdam** [aaugustin/websockets#76] opened 2015-10-28 14:35 UTC
I figured out that the client side gets timeouted every time [HERE](http://github.com/aaugustin/websockets/blob/ea5087c2a917fd6ec9a2e3954b28a548fd29c145/websockets/protocol.py#L451). This affects even the example `server.py` and `client.py` scripts.

I do not know the protocol enough to decide if this is intentional. However, smuggling `force=True` into the coro requires monkey patching that seems unelegant to me.

By defaulting `force=True` or commenting out lines 447-455 entirely, the `client.py` exits immediately after receiving the hello message which should be the good way according my intention.

**Comment by aaugustin** [comment] 2015-10-28 14:48
The server is expected to close the TCP connection right after sending the close frame as prescribed by the RFC.

If the example `server.py` doesn't, that's a bug and I should investigate it.

What OS / Python / asyncio (if applicable) / websockets versions are you using?

**Comment by SzieberthAdam** [comment] 2015-10-28 14:59
ARCH Linux 4.2.3-1 ARCH / Python 3.5.0 [GCC 5.2.0] on linux / 2.6 (installed by pip)

**Comment by aaugustin** [comment] 2015-10-28 15:03
This may be a duplicate of #73. I don't know if the Python bug discussed there was reported to bugs.python.org and fixed in Python 3.5.0.

**Comment by SzieberthAdam** [comment] 2015-10-28 15:13
Yep, sorry for not looking the past issues first. As I see the lines I refered do block the client code. By ignoring it the client's `connection_lost()` callback gets called nicely, so the server do its part by closing the connection.

For some reason the code in line 447-455 blocks the client.

**Comment by aaugustin** [comment] 2015-10-28 15:27
Yes, that's the bug (if I understand it correctly): while the server side has closed the TCP connection, asyncio doesn't dectect it on the client side and fire `connection_lost` callback.

**Comment by SzieberthAdam** [comment] 2015-10-28 16:22
I deebugged both `client.py` and `server.py` with the following code:

    import sys
    import logging
    loghandler = logging.StreamHandler(sys.stdout)
    logging.basicConfig(level=logging.DEBUG, handlers=[loghandler])
    loop = asyncio.get_event_loop()
    loop.set_debug(True)

The client receives the EOF:

    < Hello Adam
    DEBUG:asyncio:poll 9992.357 ms took 6.453 ms: 1 events
    DEBUG:asyncio:<_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>> received EOF
    INFO:asyncio:poll 9973.090 ms took 9979.426 ms: timeout

Digging into `asyncio.code` it seems that the transport is kept open [HERE](https://github.com/python/cpython/blob/d7acf9d5372447f3db62b5525d54c099c6917472/Lib/asyncio/selector_events.py#L672) and its `close()` method is not called immediately.

To be continued...

**Comment by SzieberthAdam** [comment] 2015-10-28 16:57
Well, `asyncio.streams.StreamReaderProtocol.eof_received()` has been changed since Python 3.4.3 to return True instead of None ([link](https://github.com/python/cpython/blob/d7acf9d5372447f3db62b5525d54c099c6917472/Lib/asyncio/streams.py#L242)).

According to [this](https://github.com/python/cpython/blob/d7acf9d5372447f3db62b5525d54c099c6917472/Lib/asyncio/protocols.py#L94) it means that since the change "closing the transport is up to the protocol".

**Comment by SzieberthAdam** [comment] 2015-10-28 17:15
As a quick fix, adding this method to `protocl.WebSocketCommonProtocol` solves the issue:

    def eof_received(self):
        super().eof_received()
        return None

However, making the `StreamReaderProtocol` to return `True` was intentional according to this [issue](http://bugs.python.org/issue24539), so the final solution seems to be more sophisticated.

**Comment by aaugustin** [comment] 2015-10-28 17:35
IIRC we have to be careful with SSL which handles connection termination differently. I'll review the changes in Python and try to understand how I'm supposed to adapt websockets.

**Comment by aaugustin** [comment] 2015-10-28 17:36
One last question: if you close the repository and run `make test` with your Python version, do you get test failures? You should because this is tested.

**Comment by SzieberthAdam** [comment] 2015-10-28 17:42
python -m unittest
    /usr/lib/python3.5/asyncio/tasks.py:509: DeprecationWarning: asyncio.async() function is deprecated, use ensure_future()
      DeprecationWarning)
    ................................../usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c095630>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c2e3278>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c309a90>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    ....../usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c309ef0>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c08d160>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c095f28>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c0952b0>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c079c88>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    ...../usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c08ef98>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c2e35c0>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c08ddd8>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    ./usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c08e8d0>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c0742b0>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0d159a90>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf077df128>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    ....../usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c047748>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c074358>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c309320>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0d161320>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)
    ............................................................................................................................................
    ----------------------------------------------------------------------
    Ran 192 tests in 12.156s
    
    OK
    /usr/lib/python3.5/asyncio/sslproto.py:323: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7fcf0c0aab70>
      warnings.warn("unclosed transport %r" % self, ResourceWarning)

**Comment by aaugustin** [comment] 2015-10-29 08:30
Thanks for testing. I'll investigate further as soon as I get the opportunity.

**Closed** 2015-10-31 13:11 UTC
Labels: bug
