### ISSUE TITLE
Errors with python3.7

### ISSUE THREAD

**Issue by RouquinBlanc** [aaugustin/websockets#431] opened 2018-06-27 23:01 UTC
Hi Aymeric,

I may be missing something, but it seems to me that the code is currently not yet compatible with python 3.7 (tested with top of master)

The best way to reproduce is the [first test example](https://websockets.readthedocs.io/en/stable/intro.html#browser-based-example) of the doc:

```python3.7
import asyncio
import datetime
import random
import websockets

async def time(websocket, path):
    while True:
        now = datetime.datetime.utcnow().isoformat() + 'Z'
        await websocket.send(now)
        await asyncio.sleep(random.random() * 3)

start_server = websockets.serve(time, '127.0.0.1', 5678)
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

This raises this exception:

```
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
```

I've seen you are doing some changes at the moment for python3.7, I will be happy to validate further changes. Did not catch it earlier because we were stuck with the `pyyaml` lib even earlier in our deployment... They are pushing deprecation very strongly!

**Comment by Harmon758** [comment] 2018-06-28 02:18
I'm only able to reproduce this with 5.0.1 and not the top of master.
Make sure you're up to date?

**Comment by Harmon758** [comment] 2018-06-28 05:38
No problem.
I agree, there should be a new release for 3.7 support now that 3.7.0 has been released.

**Comment by battlemidget** [comment] 2018-06-29 17:36
Hi, any eta when a new release will be pushed?

**Comment by aaugustin** [comment] 2018-06-30 11:51
Closing as a duplicate of #405.

@battlemidget No ETA on a release but I'll try to take a look at pending issues over the week-end.

**Closed by aaugustin** 2018-06-30 11:52 UTC

**Comment by aaugustin** [comment] 2018-07-01 17:29
Well, it was a nice sunny weekend, so no progress here.

**Comment by battlemidget** [comment] 2018-07-12 16:12
It's been over a week, any idea on when a new release will be published?

**Comment by aaugustin** [comment] 2018-07-14 17:49
#435 suggests that master isn't compatible with Python 3.7 yet.

**Comment by aaugustin** [comment] 2018-07-14 17:49
(which is a release blocker)

**Comment by aaugustin** [comment] 2018-07-15 09:13
#437 is another release blocker.

**Comment by aaugustin** [comment] 2018-07-16 19:56
Version 6.0 adds support for Python 3.7 and is now available on PyPI: https://pypi.org/project/websockets/6.0/#files
