### ISSUE TITLE
Make it possible to install websockets without a compiler

### ISSUE THREAD

**Issue by WilliamRusnackAtFord** [aaugustin/websockets#330] opened 2018-01-16 18:02 UTC
I'm on a corporate computer and do not have access to visual studio.
I found that I could install websockets without it by not having any extension modules in setup.py and it still seemed to work fine.
```python
 31 ext_modules = [
 32     # setuptools.Extension(
 33     #     'websockets.speedups',
 34     #     sources=['websockets/speedups.c'],
 35     #     optional=not os.path.exists(os.path.join(root_dir, '.cibuildwheel')),
 36     # )
 37 ]
```

It would be helpful if the install could detect that and disable the speedups.c from compiling.

**Comment by aaugustin** [comment] 2018-01-18 21:31
The problem with silently ignoring build failures is that users could hit unexpected performance regressions if, for any reason, the extension fails to compile but installation proceeds.

We could detect when compilation fails and provide a specific error message that explains how to install without the extension (with a flag or an environment variable).

This is very low priority for me. I will accept a pull request for this only if it's very simple. I don't like cluttering setup.py.

**Comment by mayeut** [comment] 2018-01-18 22:08
The build failure of the extension shouldn't be a problem since its marked as optional (unless you've created a `.cibuildwheel` file in the root dir. Only CI builds are doing this when building wheels). You should see the failure in the logs but as a warning only.

**Comment by aaugustin** [comment] 2018-04-28 18:46
Closing based on @mayeut's comment.

**Closed** 2018-04-28 18:45 UTC
Labels: enhancement, help wanted
