### ISSUE TITLE
Improve documentation around customizing handling of handshake

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#197] opened 2017-07-08 21:01 UTC
I was trying to figure out how to return a 404 on a bad path. Two things occur to me that would have made this a bit easier to figure out.

First, the [end of the docstring](https://github.com/aaugustin/websockets/blob/5d361a361a31ce19896dd0fb2c9dc684514e2a09/websockets/server.py#L249) of the server's `handshake()` method could be expanded to say, "Return the URI of the request, _or None if the handshake was aborted_."

Second, the [docstring of the server's `get_response_status()`](https://github.com/aaugustin/websockets/blob/5d361a361a31ce19896dd0fb2c9dc684514e2a09/websockets/server.py#L226) method could be expanded to say that the request path (e.g. to decide whether to return a 404) is available at `self.path` when that method is called.  Currently, you have to notice that `read_http_request()` is called at the beginning of `handshake()` and then see that `read_http_request()` sets `self.path`. But even then, it's not clear if you'd be relying on implementation details.

**Comment by aaugustin** [comment] 2017-07-09 15:27
Go for it and make a PR!

**Comment by cjerdonek** [comment] 2017-07-09 15:30
Okay, great. Though if you're open to my comment [here](https://github.com/aaugustin/websockets/issues/116#issuecomment-313893781) (which I wrote later), this issue would probably be subsumed.

**Comment by aaugustin** [comment] 2017-08-20 13:23
Since #248 was merged, it's time to reopen the discussion here!

**Comment by aaugustin** [comment] 2017-09-04 20:26
The section about "Port sharing" in deployment.rst should be updated, since it is now possible to implement basic HTTP responses.

**Comment by aaugustin** [comment] 2017-11-01 17:29
Since I restructured the docs, the best place to put this information would be in its own page, linked from the "howto" section in index.rst.

**Comment by aaugustin** [comment] 2018-05-05 20:44
By now, I believe this issue has become a duplicate of #354 for which I submitted PR #387.

The original issue is "I was trying to figure out how to return a 404 on a bad path."

The modern API for doing that is `process_request`, like this:

```python
    async def process_request(self, path, request_headers):
        if path != '/':
            return http.HTTPStatus.NOT_FOUND [], b'sorry not found\n'
```

This is close enough to the example in #387.

**Closed by aaugustin** 2018-05-05 20:44 UTC
Labels: documentation
