### ISSUE TITLE
when the network is bad, it shows fatal read error message

### ISSUE THREAD

**Issue by yjqiang** [aaugustin/websockets#448] opened 2018-07-28 03:23 UTC
Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x1177ce940>
transport: <_SelectorSocketTransport fd=47 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
File "/var/containers/Bundle/Application/9F565D30-C54B-4210-902B-874D7A5AB814/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/selector_events.py", line 725, in _read_ready
data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out

**Comment by aaugustin** [comment] 2018-07-29 09:16
I'm not sure what changes you're suggesting here. Do you mean that websockets should do something specific to handle this situation?

**Comment by yjqiang** [comment] 2018-07-29 09:21
Yes. As a user, I can't handle this even though I use 'try'. So I think maybe websockets should handle it.

**Comment by yjqiang** [comment] 2018-07-29 09:30
Can websockets handle this exception? I think maybe you can just drop it and retry the connection. For me the exception is very uncomfortable.

**Comment by aaugustin** [comment] 2018-07-29 10:02
OK, so that's a duplicate of #414.

**Comment by yjqiang** [comment] 2018-07-29 10:07
No, it is strange that it just show the message but "recv()" doesn't raise exceptions which means I can receive messages without reconnection.

**Comment by aaugustin** [comment] 2018-07-29 13:37
It's really hard for me to say something meaningful with zero context about what code produces this traceback under what circumstances.

**Comment by yjqiang** [comment] 2018-07-29 13:47
https://github.com/yjqiang/bilibili-live-tools/blob/master/bilibiliCilent.py

**Comment by yjqiang** [comment] 2018-07-29 13:51
1."danmuji.connectServer"  set up a connection  
2."HeartbeatLoop" and "ReceiveMessageLoop" receive the msg and heartbeat  
3. if something is wrong, then I close the connection

**Comment by yjqiang** [comment] 2018-07-31 07:50
So, do you find where the problem is?

**Comment by aaugustin** [comment] 2018-07-31 08:33
I'm not going to debug the 300 lines of code you linked to. If you can produce a minimal reproduction example that exhibits an issue in websockets, perhaps I will take a look.

**Comment by yjqiang** [comment] 2018-07-31 08:42
Ok, I'll write a minimal program. Then I will tell you. By the way, I think you should reopen this issue.

**Comment by yjqiang** [comment] 2018-08-01 11:03
Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x111208ef0>
transport: <_SelectorSocketTransport fd=12 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/9F565D30-C54B-4210-902B-874D7A5AB814/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/selector_events.py", line 725, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out
Error in data transfer
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/DD7F02C7-CB2E-4501-8454-4160BFD1B7B2/Pythonista3/Documents/site-packages-3/websockets/protocol.py", line 530, in transfer_data
    msg = yield from self.read_message()
  File "/private/var/mobile/Containers/Shared/AppGroup/DD7F02C7-CB2E-4501-8454-4160BFD1B7B2/Pythonista3/Documents/site-packages-3/websockets/protocol.py", line 582, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/private/var/mobile/Containers/Shared/AppGroup/DD7F02C7-CB2E-4501-8454-4160BFD1B7B2/Pythonista3/Documents/site-packages-3/websockets/protocol.py", line 647, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/private/var/mobile/Containers/Shared/AppGroup/DD7F02C7-CB2E-4501-8454-4160BFD1B7B2/Pythonista3/Documents/site-packages-3/websockets/protocol.py", line 712, in read_frame
    extensions=self.extensions,
  File "/private/var/mobile/Containers/Shared/AppGroup/DD7F02C7-CB2E-4501-8454-4160BFD1B7B2/Pythonista3/Documents/site-packages-3/websockets/framing.py", line 100, in read
    data = yield from reader(2)
  File "/var/containers/Bundle/Application/9F565D30-C54B-4210-902B-874D7A5AB814/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/streams.py", line 669, in readexactly
    yield from self._wait_for_data('readexactly')
  File "/var/containers/Bundle/Application/9F565D30-C54B-4210-902B-874D7A5AB814/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/streams.py", line 459, in _wait_for_data
    yield from self._waiter
  File "/var/containers/Bundle/Application/9F565D30-C54B-4210-902B-874D7A5AB814/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/var/containers/Bundle/Application/9F565D30-C54B-4210-902B-874D7A5AB814/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/tasks.py", line 245, in _wakeup
    future.result()
  File "/var/containers/Bundle/Application/9F565D30-C54B-4210-902B-874D7A5AB814/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/var/containers/Bundle/Application/9F565D30-C54B-4210-902B-874D7A5AB814/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/selector_events.py", line 725, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out

**Comment by yjqiang** [comment] 2018-08-02 01:30
Is there anything else I can do for you? Maybe my code and the message are not clearly enough, but I hope it can help you.

**Comment by yjqiang** [comment] 2018-08-05 01:33
It occurred frequently recently, it is very confusing.

**Comment by yjqiang** [comment] 2018-08-11 22:56
？

**Comment by yjqiang** [comment] 2018-08-13 13:46
Keep showing the msg...

**Comment by aaugustin** [comment] 2018-09-23 15:04
I'm sorry but I really can't help with what you've provided.

In the context of a bug report, a "minimal program" is something about as large as https://github.com/aaugustin/websockets/blob/master/example/client.py.

I suppose I could install go, compile the 638 lines of Go and run a server, connect a client with the 379 lines of Python, and see that stack trace... and I'd be left with "well I guess Go server times out somewhere".

Unfortunately I don't have the motivation to do this.

**Closed by aaugustin** 2018-09-23 15:04 UTC
Labels: question

**Comment by yjqiang** [comment] 2018-09-23 15:15
Sorry to bother u but it looks like it is a bug on Pythonista(ios). I'm so sorry about this.

**Comment by aaugustin** [comment] 2018-09-23 15:37
No problem. Feel free to open a new issue if you end up suspecting something in websockets.

**Comment by yjqiang** [comment] 2018-10-31 23:15
I’m so sorry. Sorry I just found I sent the wrong test file. But I think it’s unnecessary to resend since it’s not a bug in websockets. I wrote it just to apologize. Sorry.
