### ISSUE TITLE
Worker task not always completed if cancellation happens during close()

### ISSUE THREAD

**Issue by aldur** [aaugustin/websockets#142] opened 2016-11-15 10:58 UTC
I am investigating how to close pending tasks on exceptions.
Specifically, I extracted the following snippet of code:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import asyncio
import websockets


async def hello():
    async with websockets.connect('wss://echo.websocket.org') as websocket:
        await websocket.send("A" * 1024)
        await websocket.recv()

        raise Exception("Catch me!")

async def runner():
    tasks = [hello() for _ in range(10)]
    done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_EXCEPTION)

    if pending:
        for t in pending:
            t.cancel()
        await asyncio.wait(pending)

    for t in done:
        t.exception()  # Retrieve any exception.

asyncio.get_event_loop().run_until_complete(runner())
asyncio.get_event_loop().close()
```

Sometimes, this code results in a series of warnings as follows:

```
task: <Task pending coro=<WebSocketCommonProtocol.run() running at [...]/lib/python3.5/site-packages/websockets/protocol.py:430> wait_for=<Future pending cb=[Task._wakeup()]>>
```

Explicitly calling `close` before raising the exception helps, but does not solve the problem.

How can I manage to cleanly close the pending tasks before handling (i.e. raising) the exception?

**Comment by aaugustin** [comment] 2016-11-15 11:23
When you say "calling `close()`", do you mean `yield from websocket.close()`?

```python
try:
    # do stuff
finally:
    yield from websocket.close()
```

is supposed to avoid such errors; if they persist it's a bug.

**Comment by aldur** [comment] 2016-11-15 11:32
It turns out that in the original code I was using `await websocket.close()`, but not in the extracted snippet.

This seems to solve the pending tasks problem, however shouldn't the async context manager guarantee that the websocket is always closed, even on exceptions?

From the docs of `websockets.client.connect`:

```
On Python 3.5, connect() can be used as a asynchronous context manager. In that case, the connection is closed when exiting the context.
```

So why do we need to manually wait for it?

**Comment by aaugustin** [comment] 2016-11-15 11:49
Right, I missed the async context managed in your example. Indeed it does exactly the same thing as the `try / finally` I proposed in my previous comment.

**Comment by aaugustin** [comment] 2016-11-15 11:49
Or at least it's supposed to do exactly the same thing.

**Comment by aldur** [comment] 2016-11-15 11:57
OK so websockets by itself works as supposed, could it be a bug of the context manager?

**Comment by aaugustin** [comment] 2017-05-03 20:13
I still have no idea whether there's a bug and I don't have the motivation to investigate this further myself.

If someone can reproduce the problem and ideally isolate the root cause, that will help, and I may look into fixing it.

**Comment by cjerdonek** [comment] 2017-07-03 17:55
I just wanted to let this issue know that I'm working on providing a reduced test case.

**Comment by cjerdonek** [comment] 2017-07-03 22:13
Okay, so I looked into this, and I believe it is indeed a bug (but with a simple fix).  I will push a PR with a test case and fix momentarily.

The issue is that if `hello()` is cancelled while the websocket is calling its [`close()`](https://github.com/aaugustin/websockets/blob/5d361a361a31ce19896dd0fb2c9dc684514e2a09/websockets/protocol.py#L236) method, and if that `close()` method is waiting on the worker [at this line of code](https://github.com/aaugustin/websockets/blob/5d361a361a31ce19896dd0fb2c9dc684514e2a09/websockets/protocol.py#L258), then `close()` can return without waiting for its underlying worker to finish.

The "Task was destroyed but it is pending!" messages that can occur are referring to the task corresponding to the underlying worker (i.e. the websocket's `worker_task` instance attribute which is assigned the coroutine `WebSocketCommonProtocol.run()`), and not to the higher-level `close()` or `hello()` tasks.

The "Pending task destroyed" issue is discussed in a [special section](https://docs.python.org/3/library/asyncio-dev.html#asyncio-pending-task-destroyed) of the asyncio docs, where it says, "If a pending task is destroyed, the execution of its wrapped coroutine did not complete. It is probably a bug and so a warning is logged."

**Comment by cjerdonek** [comment] 2017-07-03 22:24
Here is the PR: https://github.com/aaugustin/websockets/pull/194

**Comment by aaugustin** [comment] 2017-09-03 18:17
I believe this happens when `worker_task` / `run()` catches `CancelledError` and continues.

**Comment by cjerdonek** [comment] 2017-09-03 19:08
Did you see my fix for this? I posted it two months ago.

**Closed** 2017-09-03 19:26 UTC
Labels: bug

**Comment by aaugustin** [comment] 2017-09-03 19:27
Yes I did!

I started working on it and eventually settled for another way to write the test. Your analysis was correct and saved me a ton of time!

**Comment by cjerdonek** [comment] 2017-09-03 20:06
Okay, thanks. But the fix seems like it's not correct to me because the `close()` task will return False for `cancelled()` after being cancelled, even though it was cancelled. This is because you're swallowing the `CancelledError` instead of letting it bubble up (or re-raising).

**Comment by aaugustin** [comment] 2017-09-03 21:19
Yes, I changed the behavior on purpose.

Catching `CancelledError` and terminating reasonably quickly is allowable. In an async world, the user has no control over the exact sequence between the moment they called `cancel()` and the moment the task terminated. 

If you look at the termination and cleanup code, in most places, it's catching `asyncio.CancelledError` / `asyncio.TimeoutError` and moving forwards with the cleanup. My change was partly driven by consistency.

I may have gotten this wrong -- backpressure and cancellation are the two hardest parts of async code -- but in that case there's a lot more than this bit of code to change. 

PS - while this wasn't a factor in my decisions, after the close frame is sent, the closing handshake cannot be "cancelled"; it's happening; so it seems a bit better from a semantic point of view if the close task's `cancelled()` method returns `False`.

**Comment by cjerdonek** [comment] 2017-09-03 22:16
Cleaning up is fine. It's just that if the task is ending early due to a cancellation (which it is), it seems better if `asyncio`'s introspection API's can properly record and reflect that fact. This will make diagnosing things easier, for example, because more information will be returned.

Python's [`asyncio.Task.cancel()` docs](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.cancel) say a bit more about this:

> **cancel()**
> Request that this task cancel itself. ... The coroutine then has a chance to clean up or even deny the request using try/except/finally.

So the docs allow cleaning up during cancellation. It's the "or even deny the request" case where `cancelled()` should return False.

On the consistency issue, yes, I noticed that, too. I'd rather see it addressed one spot at a time in a deliberate fashion, since each occurrence may take special care and tests (and it doesn't seem possible to do all at once). By proceeding incrementally, you'll also learn in the process and can accrue introspection benefits gradually. Starting the process earlier may also help unearth other issues and approaches.

**Comment by aaugustin** [comment] 2017-09-04 06:41
Okay, let's double-check and improve handling of cancellations.

Indeed, each case needs a test and it's very difficult to write good tests. Cancellation problems tend to introduce long shutdown delays or to leak pending tasks, usually depending on race conditions.

I think we need to define our general strategy, then apply it to all cases (no more that 5 of 6, if memory serves).

Let's follow up in #264.
