### ISSUE TITLE
Missing @asyncio.coroutine in client.py?

### ISSUE THREAD

**Issue by t2coo9u26k8wn** [aaugustin/websockets#434] opened 2018-07-06 00:44 UTC
I was getting the following error when running the websocket 5.0.1 client under Python 3.7.0 on Linux raspberrypi 4.14.34-v7+ but not under Eclipse on a Windows box:
`File "/usr/local/lib/python3.7/site-packages/websockets/client.py", line 397, in __await__
    transport, protocol = yield from self._creating_connection
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator`

Inserting `@asyncio.coroutine` before line 392 of client.py, just above `def __await__(self):`, fixed the error. I'm a beginner in Python so I don't know if that was intentionally missing or not.

**Comment by RemiCardona** [comment] 2018-07-06 05:41
The current release is incompatible with python 3.7, only git master is currently fixed. The next release should

**Comment by RemiCardona** [comment] 2018-07-06 05:42
The current release is incompatible with python 3.7, only git master is currently fixed. The next release will include the necessary patches. Closing as a dupe of #405. Thanks

**Closed by RemiCardona** 2018-07-06 05:42 UTC

**Comment by aaugustin** [comment] 2018-07-16 19:56
Version 6.0 adds support for Python 3.7 and is now available on PyPI: https://pypi.org/project/websockets/6.0/#files
