### ISSUE TITLE
Logging is not working with Django

### ISSUE THREAD

**Issue by sphinxxanxus** [aaugustin/websockets#1047] opened 2021-09-12 11:48 UTC
Hello there. You are doing great work.
I am using `Django=3.2.5` with `websockets==10.0`. I am trying to log the exceptions but It doesn't work when I tried to connect.

here is my configuration
```python
import logging

quatro_sentinel_logger = _logging.getLogger('quatro.sentinel')


class LoggerAdapter(logging.LoggerAdapter):
    """Add connection ID and client IP address to websockets logs."""
    def process(self, msg, kwargs):
        try:
            websocket = kwargs["extra"]["websocket"]
        except KeyError:
            return msg, kwargs
        xff = websocket.request_headers.get("X-Forwarded-For")
        return f"{websocket.id} {xff} {msg}", kwargs


class Sentinel:
 ...
async def start(self, addr, port, **kwargs):
    """ This function ensures starting the server"""
    print("Starting sentinel")
    async with websockets.serve(
            self.get_handler(), addr, port, ping_interval=5, ping_timeout=2,
            logger=LoggerAdapter(quatro_sentinel_logger, {}), **kwargs
    ):
        await asyncio.Future()
....

``` 
The server starts without any errors but I am unable to connect
![server response](https://user-images.githubusercontent.com/38927111/132986239-c9cba516-398e-4847-a11e-fbfa8ffefae7.png)

The connection is closed when I tried to connect. But the server is still runging
![client response](https://user-images.githubusercontent.com/38927111/132986266-259c6736-708a-408d-94e0-5159cd874346.png)

**Comment by aaugustin** [comment] 2021-09-13 20:34
I'm not seeing anything wrong in what you provided. You should try to get additional debug information. Try enabling debug logs to see what happens — https://websockets.readthedocs.io/en/stable/howto/cheatsheet.html#debugging — of course this may not work well if the issue is with logging in the first place...

**Comment by sphinxxanxus** [comment] 2021-09-13 21:34
By default in dev, the default level of my loggers is `DEBUG`.

```
              ....
                'quatro.sentinel': {
                    'level': 'DEBUG',
                    'handlers': ['file_quatro_sentinel', 'console'],
                    'propagate': False,
                },
               ...
```

I load it dynamically into the Django `LOGGING` settings.

**Comment by sphinxxanxus** [comment] 2021-09-13 22:09
```
(venv) ➜  Unicore git:(master) ✗ python -m websockets  ws://127.0.0.1:8765 
> <Logger websockets.client (WARNING)>
<LoggerAdapter websockets.client (WARNING)>
b''
line without CRLF
connection closed while reading HTTP status line
Failed to connect to ws://127.0.0.1:8765: did not receive a valid HTTP response.
(venv) ➜  Unicore git:(master) ✗ python -m websockets  ws://127.0.0.1:8765
<Logger websockets.client (WARNING)>
> <LoggerAdapter websockets.client (WARNING)>
b'HTTP/1.1 101 Switching Protocols\r\n'
b'Upgrade: websocket\r\n'
b'Connection: Upgrade\r\n'
b'Sec-WebSocket-Accept: VpncMpkp65PPpGWcMZJuglJWbXw=\r\n'
b'Sec-WebSocket-Extensions: permessage-deflate; server_max_window_bits=11; client_max_window_bits=11\r\n'
b'Date: Mon, 13 Sep 2021 21:57:00 GMT\r\n'
b'Server: Python/3.9 websockets/10.0\r\n'
b'\r\n'
Connected to ws://127.0.0.1:8765.
Connection closed: 1011 (unexpected error) {"error": "No authentication token provided."}.
````

What I noticed is that when I registered a custom logger the headers of upgrading the HTTP request is empty.
I didn't check where it is coming from but it may help.

**Comment by aaugustin** [comment] 2021-09-16 21:49
I'm afraid I'm not going to be able to debug this efficiently with the information you provided.

From my old days as a Django core dev, I remember that Django's logging configuration doesn't work well for legacy reasons (basically because Django configures logging twice but logging doesn't support reconfiguration). Try `LOGGING_CONFIG = None` and configuring logging outside of Django?

If you can get websockets' logs to work with `logging.config.dictConfig()`, then it isn't a bug in websockets.

**Comment by corentinalcoy** [comment] 2021-09-17 15:35
I tested with `logging.config.dictConfig()`, it is working but not with Django's logging. 
I will try to review the way that I define the logger for my websocket app.

**Comment by corentinalcoy** [comment] 2021-09-17 15:36
I know it is not the right place to tell this but there is an issue with the [echo server tutorial](https://websockets.readthedocs.io/en/latest/index.html). The signature should be 
`async def echo(websocket, path):`. Without the `path` parameter, I have the error below when I am trying to connect.

```
connection handler failed
Traceback (most recent call last):
  File "/home/petitnokoue/PycharmProjects/radix-shopify/venv/lib/python3.9/site-packages/websockets/legacy/server.py", line 224, in handler
    await self.ws_handler(self, path)
TypeError: echo() takes 1 positional argument but 2 were given
```

**Comment by aaugustin** [comment] 2021-09-17 17:17
> there is an issue with the echo server tutorial. 

You are looking at the "lastest" docs while using the 10.0 version of websockets. You should do one of the following:

- look at the "stable" docs (which are currently for 10.0)
- checkout the code and use the main branch (which corresponds to the "latest" docs)

**Comment by aaugustin** [comment] 2021-09-17 17:41
If your logging config doesn't contain `'disable_existing_loggers': False,` adding it could help.

**Comment by aaugustin** [comment] 2021-10-30 06:38
I'm going to close this issue because the information in this thread suggests that websockets isn't at fault.

If you land here because you have the same problem, I would recommend that you read this very carefully:
https://docs.djangoproject.com/en/stable/topics/logging/#configuring-logging

**Closed by aaugustin** 2021-10-30 06:38 UTC
Labels: question
