### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [aaugustin/websockets#846] opened 2020-11-02 08:40 UTC
**Summary**
Installing websockets on aarch64 via pip using command "pip3 install websockets" tries to build wheel from source code.

**Problem description**
websockets doesn't have wheel for aarch64 on PyPI repository. So, while installing websockets via pip on aarch64, pip builds wheel for same resulting in it takes more time to install websockets. Making wheel available for aarch64 will benefit aarch64 users by minimizing websockets installation time.

**Expected Output**
Pip should be able to download websockets wheel from PyPI repository rather than building it from source code.

@websockets-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make websockets wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by aaugustin** [comment] 2020-11-03 16:29
Duplicate of #815, I believe.

**Closed** 2020-11-21 12:39 UTC
Labels: duplicate
