### ISSUE TITLE
Legacy reference import error

### ISSUE THREAD

**Issue by drc38** [aaugustin/websockets#1063] opened 2021-10-05 21:31 UTC
Hi, are you able to help with understanding why we get the following import error. It started happening for users when we went to websockets 10. 
Many thanks 
```
Error setting up entry central for ocpp
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ocpp/__init__.py", line 28, in async_setup_entry
    central_sys = await CentralSystem.create(hass, entry)
  File "/config/custom_components/ocpp/api.py", line 137, in create
    server = await websockets.serve(
  File "/usr/local/lib/python3.9/site-packages/websockets/imports.py", line 81, in __getattr__
    source = deprecated_aliases[name]
  File "/usr/local/lib/python3.9/site-packages/websockets/imports.py", line 26, in import_name
    assert level < len(source), "importing from parent isn't supported"
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/server.py", line 26, in <module>
    from ..connection import State
  File "/usr/local/lib/python3.9/site-packages/websockets/connection.py", line 17, in <module>
    from .frames import (
ImportError: cannot import name 'OK_CLOSE_CODES' from 'websockets.frames' (/usr/local/lib/python3.9/site-packages/websockets/frames.py)
```

**Comment by aaugustin** [comment] 2021-10-06 07:53
This doesn't look good. Do you have an easy way for me to reproduce?

If I do:

```python
import websockets

await websockets.serve(...)
```

I don't get this error.

There's another factor at play and it will be hard to spot if I cannot reproduce.

**Comment by drc38** [comment] 2021-10-07 05:08
Reproducing it might be challenging given the code is implemented in the Home Assistant environment. I'm awaiting feedback if the error occurs when those users affected specify websockets 9.1 instead.

It strikes me as odd the traceback references the "legacy" version of server.py, what determines whether the use of any "legacy" code?

**Comment by aaugustin** [comment] 2021-10-07 07:25
If you do this:

```python
import websockets.server

await websockets.server.server(...)
```

it will very likely fix the problem. However, that shouldn't be necessary, so I'd like to understand what's happening.

**Comment by drc38** [comment] 2021-10-09 01:02
Users have confirmed that if they go back to 9.1 there is no issue. If they then specify websockets 10.0 having previously been on 9.1 there is also no issue. So it appears to occur on a fresh install of 10.0 only?

**Comment by aaugustin** [comment] 2021-10-09 07:03
This suggests that the upgrade mechanism is unclean, which is worrying. An upgrade should wipe entirely the previous version before installing the new one.

**Comment by aaugustin** [comment] 2021-10-30 05:57
Since you seem to be happy with the workaround and I don't have a clear path for investigating further, I'm going to close this issue. There's something fishy here but I have no idea what.

**Closed by aaugustin** 2021-10-30 05:57 UTC
