### ISSUE TITLE
Using yield from in Python 3.7 causes TypeError

### ISSUE THREAD

**Issue by asnelzin** [aaugustin/websockets#435] opened 2018-07-10 09:38 UTC
Library what I use is using `yield from` with `websockets.connect` in Python 3.7 
```
yield from websockets.connect(self.address)
```
I am getting an error: `TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator`

As I can see, in Python 3.7 `loop.create_connection` is now a native coroutine, so you can not `yield from` it. Maybe we can mark `__iter__` with `@asyncio.coroutine` not only for Python < 3.5?

NB: I am using master version websockets @ `39b050fc8`

**Comment by RemiCardona** [comment] 2018-07-11 16:06
The current release is incompatible with python 3.7, only git master is currently fixed. The next release will include the necessary patches. Closing as a dupe of #405. Thanks

**Comment by RemiCardona** [comment] 2018-07-11 16:35
Reopening then. Please do try to provide a PR for this, as travis may be able to help test all python versions we care about. Thanks.

**Comment by aaugustin** [comment] 2018-07-15 08:53
Interestingly, we don't have a test for this use case.

**Comment by aaugustin** [comment] 2018-07-15 09:07
Thank you @asnelzin for reporting this issue — and preventing me from embarrassing myself _again_.

I could reproduce it. Your suggestion seems to fix it. I'm working on it.

**Comment by aaugustin** [comment] 2018-07-15 09:13
I need to tackle #437 so that CI can prevent regressions on Python 3.7 in the future.

**Closed** 2018-07-15 11:10 UTC
Labels: bug

**Comment by aaugustin** [comment] 2018-07-16 19:56
Version 6.0 adds support for Python 3.7 and is now available on PyPI: https://pypi.org/project/websockets/6.0/#files

**Comment by asnelzin** [comment] 2018-07-17 09:14
Thank you!
