### ISSUE TITLE
ImportError: cannot import name 'CLOSED' from 'websockets.connection'

### ISSUE THREAD

**Issue by brunohjs** [aaugustin/websockets#1328] opened 2023-04-03 22:07 UTC
I found a problem with version `v11.0` (launched yesterday). I don't know how to solve this problem from current version, but I downgraded to `v10.4` to keep using the lib. 
Related post: https://stackoverflow.com/questions/75913380/importerror-cannot-import-name-closed-from-websockets-connection

![DeepinScreenshot_select-area_20230403185751](https://user-images.githubusercontent.com/26513013/229637329-f34a97a2-0fb8-43b4-9401-11bc494e727e.png)

**Comment by aaugustin** [comment] 2023-04-04 05:31
I submitted changes to Sanic in November to prevent this issue:
https://github.com/sanic-org/sanic/commit/4c14910d5bbbbb6e12c1860572ecdc5c198f9b7e

Sanic has had two releases since then. Can you check that you're using the latest version of Sanic, please?

If you're sticking to an old version of Sanic, you have to stick to an old version of websockets. Indeed, Sanic used to rely on implementation details of websockets, before I submitted changes to rely on the public API.

**Comment by aaugustin** [comment] 2023-04-04 05:33
Duplicate of https://github.com/sanic-org/sanic/issues/2733

**Closed by aaugustin** 2023-04-04 05:33 UTC

**Comment by brunohjs** [comment] 2023-04-04 13:10
> I submitted changes to Sanic in November to prevent this issue: [sanic-org/sanic@4c14910](https://github.com/sanic-org/sanic/commit/4c14910d5bbbbb6e12c1860572ecdc5c198f9b7e)
> 
> Sanic has had two releases since then. Can you check that you're using the latest version of Sanic, please?
> 
> If you're sticking to an old version of Sanic, you have to stick to an old version of websockets. Indeed, Sanic used to rely on implementation details of websockets, before I submitted changes to rely on the public API.

It's true. My Sanic isn't the latest version. Thank you very much @aaugustin!
