### ISSUE TITLE
Websocket Server: Closing handshake failed in v10, v9.1 was ok 

### ISSUE THREAD

**Issue by chuckyblack** [aaugustin/websockets#1072] opened 2021-10-16 17:09 UTC
Hello Augustin,
from version 10 occurs an error during closing browser tab connected to my websocket server.
It occurs only in approximately 30% cases.
But everything was ok in version 9.1.

Tested in Google Chrome 94.

Traceback:
```
closing handshake failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/server.py", line 232, in handler
    await self.close()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 779, in close
    await asyncio.shield(self.close_connection_task)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1309, in close_connection
    self.transport.write_eof()
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 972, in write_eof
    self._sock.shutdown(socket.SHUT_WR)
OSError: [Errno 107] Socket not connected
```

Websocket server simplified code:
```python
import asyncio
import signal
import websockets
import sys


class Chat(object):
	async def process(self, websocket: websockets.WebSocketServerProtocol, path: str):
		async for event in websocket:
			print(event)
			sys.stdout.flush()

	__call__ = process


async def server(stop):
	async with websockets.serve(Chat(), "0.0.0.0", 8765):
		await stop


if __name__ == "__main__":
	loop = asyncio.get_event_loop()
	stop = loop.create_future()
	loop.add_signal_handler(signal.SIGTERM, stop.set_result, None)
	loop.run_until_complete(server(stop))

```

Can you help me, please?

Thanks a lot,
Jaromir

**Comment by aaugustin** [comment] 2021-10-17 08:21
Looks like a bug. Probably websockets should ignore exceptions there.

**Comment by aaugustin** [comment] 2021-10-30 06:32
I tried to reproduce this error but I didn't manage. I didn't find any changes in this area between 9.1 and 10.0 either. So I have no idea why it's happening in 10.0 but didn't happen before :-(

This change could help. Would someone who hits the issue be able to test if it helps, please?

```diff
diff --git a/src/websockets/legacy/protocol.py b/src/websockets/legacy/protocol.py
index a31a5c7..9c0819c 100644
--- a/src/websockets/legacy/protocol.py
+++ b/src/websockets/legacy/protocol.py
@@ -1303,7 +1303,7 @@ class WebSocketCommonProtocol(asyncio.Protocol):
                     self.logger.debug("! timed out waiting for TCP close")

             # Half-close the TCP connection if possible (when there's no TLS).
-            if self.transport.can_write_eof():
+            if self.transport.can_write_eof() and not self.transport.is_closing():
                 if self.debug:
                     self.logger.debug("x half-closing TCP connection")
                 self.transport.write_eof()
```

**Comment by aaugustin** [comment] 2021-11-03 19:59
Is anyone able to test this patch? If you have a way to reproduce the issue, it should take only of few minutes to apply this change and check if the issue goes away 🙏

**Comment by Catastropha** [comment] 2021-11-03 20:44
I'll try to test it.

The error indeed happens at line 1308 in protocol.py


   1. # Half-close the TCP connection if possible (when there's no TLS).
   2. if self.transport.can_write_eof():
   3. if self.debug:
   4. self.logger.debug("x half-closing TCP connection")
   5. self.transport.write_eof()

**Comment by ngnpope** [comment] 2021-11-05 12:10
@aaugustin I can confirm that your patch above fixes the issue.

<details>

<summary>Before</summary>

```
2021-11-05 11:54:06,881 [ERROR] websockets.server:175 run_asgi - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 171, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/asgi2.py", line 17, in __call__
    await instance(receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 100, in inner
    return await self._run_app(scope, lambda: self.app(scope)(receive, send))
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 152, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 149, in _run_app
    return await callback()
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 100, in <lambda>
    return await self._run_app(scope, lambda: self.app(scope)(receive, send))
  File "/usr/local/lib/python3.9/site-packages/channels/routing.py", line 54, in __call__
    return self.application_mapping[scope["type"]](scope)
  File "/usr/local/lib/python3.9/site-packages/channels/security/websocket.py", line 37, in __call__
    return self.application(scope)
  File "...", line 39, in __call__
    return self.inner(scope)
  File "/usr/local/lib/python3.9/site-packages/channels/sessions.py", line 47, in __call__
    return self.inner(dict(scope, cookies=cookies))
  File "/usr/local/lib/python3.9/site-packages/channels/sessions.py", line 145, in __call__
    return SessionMiddlewareInstance(scope, self)
  File "/usr/local/lib/python3.9/site-packages/channels/sessions.py", line 169, in __init__
    self.inner = self.middleware.inner(self.scope)
  File "/usr/local/lib/python3.9/site-packages/channels/middleware.py", line 31, in __call__
    inner_instance = self.inner(scope)
  File "/usr/local/lib/python3.9/site-packages/channels/routing.py", line 150, in __call__
    raise ValueError("No route found for path %r." % path)
ValueError: No route found for path 'api/stream/invalid/'.
2021-11-05 11:54:06,883 [INFO] websockets.server:633 handshake - connection open
2021-11-05 11:54:06,884 [ERROR] websockets.server:236 handler - closing handshake failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/server.py", line 232, in handler
    await self.close()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 779, in close
    await asyncio.shield(self.close_connection_task)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1309, in close_connection
    self.transport.write_eof()
  File "uvloop/handles/stream.pyx", line 696, in uvloop.loop.UVStream.write_eof
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x562533123c10>; the handler is closed
2021-11-05 11:54:06,887 [INFO] websockets.server:252 handler - connection closed
```

</details>

<details>

<summary>After</summary>

```
2021-11-05 11:55:21,095 [ERROR] websockets.server:175 run_asgi - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 171, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/asgi2.py", line 17, in __call__
    await instance(receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 100, in inner
    return await self._run_app(scope, lambda: self.app(scope)(receive, send))
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 152, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 149, in _run_app
    return await callback()
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 100, in <lambda>
    return await self._run_app(scope, lambda: self.app(scope)(receive, send))
  File "/usr/local/lib/python3.9/site-packages/channels/routing.py", line 54, in __call__
    return self.application_mapping[scope["type"]](scope)
  File "/usr/local/lib/python3.9/site-packages/channels/security/websocket.py", line 37, in __call__
    return self.application(scope)
  File "...", line 39, in __call__
    return self.inner(scope)
  File "/usr/local/lib/python3.9/site-packages/channels/sessions.py", line 47, in __call__
    return self.inner(dict(scope, cookies=cookies))
  File "/usr/local/lib/python3.9/site-packages/channels/sessions.py", line 145, in __call__
    return SessionMiddlewareInstance(scope, self)
  File "/usr/local/lib/python3.9/site-packages/channels/sessions.py", line 169, in __init__
    self.inner = self.middleware.inner(self.scope)
  File "/usr/local/lib/python3.9/site-packages/channels/middleware.py", line 31, in __call__
    inner_instance = self.inner(scope)
  File "/usr/local/lib/python3.9/site-packages/channels/routing.py", line 150, in __call__
    raise ValueError("No route found for path %r." % path)
ValueError: No route found for path 'api/stream/invalid/'.
2021-11-05 11:55:21,100 [INFO] websockets.server:633 handshake - connection open
2021-11-05 11:55:21,100 [INFO] websockets.server:252 handler - connection closed
```

</details>

**Comment by DmytroLitvinov** [comment] 2021-11-05 12:49
In case if someone is interested to compare [changes from v9.1 to v10](https://github.com/aaugustin/websockets/compare/9.1...10.0)

**Comment by ngnpope** [comment] 2021-11-05 13:23
For some more background, this issue occurred for me when upgrading `uvloop` from `0.15.3` to `0.16.0` and `websockets` from `9.1` to `10.0`. I've tested downgrading each of the packages independently and can confirm that the error is caused by the upgrade to `websockets==10.0`.

**Comment by aaugustin** [comment] 2021-11-05 13:29
Thanks a lot for your help! I'll commit the fix shortly.

**Comment by aaugustin** [comment] 2021-11-05 13:29
(I'd still love if someone had a way to reproduce on macOS because I swear I tried a dozen combos of clients x ways to break the connection and never reproduced this.)

**Comment by ngnpope** [comment] 2021-11-05 13:37
I'm not very familiar with the bit of code that I'm looking into right now so not sure how much help I can be.

In my example above I triggered an exception:

```
ValueError: No route found for path 'api/stream/invalid/'.
```

So it looks like we're seeing the following because the connection is terminated abnormally:

```
2021-11-05 11:54:06,884 [ERROR] websockets.server:236 handler - closing handshake failed
```

Not sure if that is helpful. I was able to trigger this behaviour easily with the following where the path isn't valid:

```
wscat --connect=ws://127.0.0.1:3000/api/stream/invalid/
```

**Comment by timvandermeij** [comment] 2021-11-05 18:47
I also ran into this problem with `websockets` 10.0 in combination with `uvloop` and I can confirm that the change in https://github.com/aaugustin/websockets/issues/1072#issuecomment-955159232 fixes the problem on Debian Buster (and also that `websockets` 9.1 didn't have the issue). Hopefully this fix can be merged and released since I now had to downgrade to version 9.1 for the time being.

Thank you for your efforts in developing the `websockets` library!

**Comment by aaugustin** [comment] 2021-11-14 20:15
Version 10.1, which includes the fix, is available on PyPI. Thanks everyone for your help!

**Comment by 1007tejas** [comment] 2021-11-15 13:07
aaugustin,

Maybe this will help.

behavior:
Clicking on a different tab of a web page running inside QT5 dumps  and reloads the websockets javascript client closing the Transport endpoint.

websockets client js environment: running in Qt5/Pyside2 with included Chrome browser
websockets version 10.1
python3.8
os linuxmint

js: websocket client listens to events 'onopen','onclose','onmessage' and 'onerror'.

error output:
js: WebSocket connection is up

stack trace:

closing handshake failed
Traceback (most recent call last):
  File "/home/jeff/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 239, in handler
    await self.close()
  File "/home/jeff/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 780, in close
    await asyncio.shield(self.close_connection_task)
  File "/home/jeff/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1309, in close_connection
    self.transport.write_eof()
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 964, in write_eof
    self._sock.shutdown(socket.SHUT_WR)
OSError: [Errno 107] Transport endpoint is not connected

output:
js: WebSocket connection is up

observation:
    time.sleep(2) before line 1309 worked, eliminating the OSError. It seems to indicate a slow update of status  transport.is_closing() and perhaps others.

work around:
    catch the OSError
        protocol.py line 1309: `self.transport.write_eof()` enclosed in try/except
                # except OSError as error :
                # try:
                #     self.transport.write_eof()
                # except OSError as error :
                #     if self.debug:
                #         self.logger.debug(f"! OSError: {error}")
                # finally:
                #     pass

The Pyside2 environment probably affected the issue's timing, but hopefully sheds some light on the overall problem.

**Comment by ChronoDK** [comment] 2022-03-14 09:46
I believe this error has resurfaced in 10.2. 

10.1 is working fine, but 10.2 is giving me this error, when a connection is non-gracefully closed:

> [ERROR] closing handshake failed
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/websockets/legacy/server.py", line 240, in handler
> await self.close()
> File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 779, in close
> await asyncio.shield(self.close_connection_task)
> File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1312, in close_connection
> self.transport.write_eof()
> File "uvloop/handles/stream.pyx", line 696, in uvloop.loop.UVStream.write_eof
> File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
> RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x55ee6d824e80>; the handler is closed

**Comment by ngnpope** [comment] 2022-03-14 10:32
I can confirm that this as resurfaced for me as of 5b3a6d26c493f1aa54d267223ba3a908f0793fc8 in v10.2.

**Comment by ngnpope** [comment] 2022-04-04 08:20
Hi @aaugustin 

Was wondering if any progress had been made on this one? Would you like me to open a PR reinstating the `not self.transport.is_closing()` condition?

I also noticed some other changes in the `main` branch yesterday related to closing stuff. Is that related to this in any way?

Thanks 🙂

**Comment by aaugustin** [comment] 2022-04-04 16:13
I am not clear on how I want to handle this :-(

Yesterday's changes are related to the Sans-I/O implementation which isn't involved here.

**Comment by ngnpope** [comment] 2022-04-04 18:56
OK. Thanks for the update 😢

**Comment by aaugustin** [comment] 2022-04-17 11:29
I decided to keep https://github.com/aaugustin/websockets/commit/5b3a6d26c493f1aa54d267223ba3a908f0793fc8, else #1117 would come back, and just catch `RuntimeError` to support uvloop.

**Closed** 2022-04-17 11:29 UTC
Labels: bug, high priority
