### ISSUE TITLE
Best practices for ingesting high frequency data

### ISSUE THREAD

**Issue by nickmachairas** [aaugustin/websockets#919] opened 2021-03-14 16:47 UTC
Hello, let me start by saying thank you for the great work on this library. I've been obsessively going through different possible solutions to my problem the past week and the quality of this library really stands out.

Much of what I will present below has been discussed in other closed issues but not in one place and not with these problems (to my knowledge). Perhaps this record will also help others in my position. Here it goes...

I've been working with Python for data analysis for several years now and recently decided to learn how to set up systems for high-frequency message ingestion and analysis, for IoT and financial applications (not crypto!). I am still learning and, yes, I know Python might prove too slow for this use case.

So I signed up with polygon.io since their stock websocket stream would provide plenty of messages for testing (and learning). As of this writing they offer four streams (A, AM, T, Q), one can subscribe to either or all at a time, I think. I am focusing on the "A. *" stream which delivers per-second aggregates. I observed an average of ~550 msg/sec throughout the day with some occasional spikes of ~1250 msg/sec. I read that the "T. *" stream can peak at ~2M msg/sec but I haven't touched it. I am intrigued though, once I develop my skills. Each message is sending a single event as ``[{"ev":"A", "sym":"MSFT", "v":123, ...}]`` and it is stated that if the client is slow in handling the messages they will be sent with 2+ events as ``[{"ev":"A", "sym":"MSFT", "v":123, ...},{"ev":"Q", "sym":"AAPL", "v":456, ...},...]``.

Polygon has a very basic Python example ingesting data from the streams using the ``websocket_client`` library and threading. I find ``websockets`` and ``asyncio`` to be a far better solution and this was my initial implementation. I should mention that this script pushed the messages to a TimescaleDB instance, I am now working on publishing the messages to a Kafka instance.

```python
async def stream():
    async with websockets.connect(POLYGON_URI, ssl=True) as websocket:
        # authenticate
        await websocket.send(
            '{"action":"auth","params":"' + POLYGON_KEY + '"}')
        # subscribe
        await websocket.send(
            '{"action":"subscribe","params":"A.*"}')

        # Here I just want to remove the three status messages from processing
        # Perhaps there is a better way?
        greet = await websocket.recv()
        auth = await websocket.recv()
        sub = await websocket.recv()
        print(greet, auth, sub)  # <-- replace with log

        # message handling
        async for message in websocket:
            # do something with each message... (i.e. insert to DB, publish to MQ, etc.)
```

Simple, right? The connection was rock solid for the most part except for the "high trading activity" hours, namely 9:30-10:30am and 3:30-4:00pm where my connection would constantly drop with error 1006. What was particularly puzzling was that I did not notice a dramatic 2x, 3x message increase during these hours, maybe a 10-25% increase. I was constantly monitoring my computer's resources, the script was running on 6 threads (out of the available 24) and CPU usage never near 100%.

I haven't done a lot of testing yet but it appears that setting ``ping_timeout=None`` and ``max_queue`` to a high enough number keeps the connection alive throughout the day. For what it's worth, the connection seemed more stable on my personal rig than the GCP VMs that I tested (proxies, clock speed??). I'd really like to understand what's happening though, how I can optimize the process and how I can figure out what the limitations of Python are where adding more memory or CPU resources won't make a difference and moving on to a different language such as Go would be more appropriate. Is there a way to print/log and inspect the queue size as the messages are coming in? Are there any best practices for parsing messages in the async loop? Could my inserts to TimescaleDB be slowing down the process? Any advice on how to best troubleshoot?

Apologies for the question barrage, any input would be much appreciated. Again, great work with this library. Thanks!

**Comment by aaugustin** [comment] 2021-03-14 21:00
> it appears that setting ping_timeout=None and max_queue to a high enough number keeps the connection alive throughout the day.

That makes sense.

Currently `websockets` doesn't provide metrics on buffer size or queues size; as a consequence you're shooting in the dark to optimize these things :-(

For debugging:

- you can try `print(len(websocket.messages))` — it's a private API but it will give you a figure to compare against `max_queue`
- you can try `pong_waiter = await websocket.ping()`, then start a task to `await pong_waiter`, and log how long it took to get the pong — that will give you a figure to compare against `ping_timeout`.

I'm super interested in hearing about what you learn because I never used websockets in such circumstances.

The hard point with your design is that:

- you cannot shard the stream (à la Kafka) so you have to do everything in a single process
- Python doesn't scale nicely to multiple threads; in fact, if you're CPU bound, it doesn't scale at all; if you're I/O bound, likely it will be faster to do everything in the same OS thread. In theory, Go is supposed to do better, because it was designed from the start with a scheduler that can multiplex coroutines onto OS threads.

I don't know how you insert in TimescaleDB; if you believe this is the bottleneck, or even better if your benchmarks prove it, perhaps that's a good target (e.g. can you batch inserts and what's the best size for stability?)

**Comment by nickmachairas** [comment] 2021-03-15 00:38
Many thanks for the advice, Aymeric! I will certainly let you know how it goes this week. It has been a very interesting learning journey so far. My plan was to just process per-minute messages but I got a bit obsessed once I saw I could get per-second, or even more frequent messages. Not that I'd know what to do with every trade coming out of the tapes even if I could grab every single one but I appreciate the challenge.

The goal is to identify the limitations in the Python implementation, as well as understand TCP and websockets a bit better. I was expecting the limit to be in the 10-20k msg/sec range, no math, just a hunch.

I don't think TimescaleDB is the bottleneck, 2000 msg/sec is an easy threshold to cross given the resources I have assigned. It is bad design though and that's why I will replace it with Kafka. You raise an interesting point about threading, is there a way to control the number of threads?

Cheers!

**Comment by teamun1corn** [comment] 2021-03-17 01:07
And soon you'll be handling 130 million messages per day without a sweet :) good luck on your journey my friend!

**Comment by aaugustin** [comment] 2021-05-01 21:11
Marking as a low priority enhancement - providing metrics to facilitate optimization.

**Comment by folktale42** [comment] 2021-05-11 08:15
@nickmachairas, cheers mate. Interested in knowing if you ever compared websockets to an equivalent Go implementation and if there is too much of a difference in performance.

**Comment by aaugustin** [comment] 2021-05-15 07:02
I think there's room for better documentation here.

@nickmachairas Does #957 help?

**Comment by nickmachairas** [comment] 2021-05-15 17:15
Sorry about the delay. @folktale42 my final implementation for ingesting messages was in Go using gorilla websocket. Orders of magnitude faster but this has to do with the fundamental differences between Go and Python. This Python library here is a much better maintained and documented project than gorilla.

And while I still consider myself a Pythonista, I must admit I am really enjoying Go coroutines.

@aaugustin sounds good how can I help? I have a system in place now where I can process upwards of 40,000msg/sec and can run various benchmarks. Also, going back to my original post, the main problem there was a silly mistake where I was waiting for confirmation of successful publish to the message queue for each message.

**Comment by bsergean** [comment] 2021-05-25 21:26
For what it's worth I wrote some kind of Websocket benchmark (mostly receiving messages as fast as possible) which was using multiple implementations in various languages.

https://github.com/bsergean/autoroute

iirc most languages were 'good enough' and pretty fast. I wrote a server built on this library which had processed a lots of messages over a few years now.

**Comment by nickmachairas** [comment] 2021-05-28 03:21
@bsergean Nice work! Not sure if I am missing something but I don't see results for Go which you listed at the top of the repo. Also some of the links you have there do not match the referenced language.

**Comment by bsergean** [comment] 2021-05-28 17:36
Thanks @nickmachairas / if you want to leave issues or PR there I can improve things. The benchmark was made so that anyone with docker can run it so if you are docker savvy you could run it yourself.

**Comment by aaugustin** [comment] 2021-05-28 20:01
I believe the documentation I added in 58ac522 and issue #958 adequately cover everything actionable here.

I'll wait a few more days to see if something else comes up before closing this issue.

**Closed** 2021-06-06 20:37 UTC
Labels: documentation
