### ISSUE TITLE
Deprecation error in the legacy module with Python3.10

### ISSUE THREAD

**Issue by ytrezq** [aaugustin/websockets#1029] opened 2021-08-13 09:59 UTC
File "/usr/local/lib/python3.10/site-packages/web3/providers/websocket.py", line 72, in __aenter__
        self.ws = await connect(
      File "/usr/lib64/python3.10/site-packages/websockets/legacy/client.py", line 622, in __await_impl__
        transport, protocol = await self._create_connection()
      File "/usr/lib64/python3.10/asyncio/base_events.py", line 1080, in create_connection
        transport, protocol = await self._create_connection_transport(
      File "/usr/lib64/python3.10/asyncio/base_events.py", line 1098, in _create_connection_transport
        protocol = protocol_factory()
      File "/usr/lib64/python3.10/site-packages/websockets/legacy/client.py", line 160, in __init__
        super().__init__(**kwargs)
      File "/usr/lib64/python3.10/site-packages/websockets/legacy/protocol.py", line 154, in __init__
        self._drain_lock = asyncio.Lock(
      File "/usr/lib64/python3.10/asyncio/locks.py", line 77, in __init__
        super().__init__(loop=loop)
      File "/usr/lib64/python3.10/asyncio/mixins.py", line 17, in __init__
        raise TypeError(
    TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary

**Comment by aaugustin** [comment] 2021-08-14 09:30
Duplicate of #1018.

**Closed by aaugustin** 2021-08-14 09:30 UTC
