### ISSUE TITLE
Basic example issue: Cannot write to a WebSocket in the CLOSING state

### ISSUE THREAD

**Issue by brianblakewong** [aaugustin/websockets#339] opened 2018-01-28 07:33 UTC
I'm running the basic example from here: https://websockets.readthedocs.io/en/stable/intro.html

When I run the client program, about 30% of the time I get an error (after successfully printing the greeting from the server):

```
> Brian
< Hello Brian!
Traceback (most recent call last):
  File "test_websockets_client.py", line 12, in <module>
    asyncio.get_event_loop().run_until_complete(hello())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "test_websockets_client.py", line 10, in hello
    print('< {}'.format(greeting))
  File "/Users/brianwong/evex-python2/websockets/client.py", line 390, in __aexit__
    yield from self.ws_client.close()
  File "/Users/brianwong/evex-python2/websockets/protocol.py", line 370, in close
    self.timeout, loop=self.loop)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/Users/brianwong/evex-python2/websockets/protocol.py", line 642, in write_frame
    "in the {} state".format(self.state.name))
websockets.exceptions.InvalidState: Cannot write to a WebSocket in the CLOSING state
```

All help very much appreciated!

**Comment by feridM** [comment] 2018-03-21 13:44
Reply is a little late, but better now than never.
The code breaks on the await command:
`
 await websocket.send(greeting)
    print("> {}".format(greeting))
`
Which Python version do you use to start the program? It looks like it is a python2 version. Is the server running at the same time?

**Comment by CookiesBestDinner** [comment] 2018-04-12 23:15
@feridM it says python3.6 in the directories mentioned
It doesn't break on await send, that has already finished (the context manager is exiting)

The error message shows that the connection state is CLOSING
`write_frame(OP_CLOSE, data)` is the only thing setting CLOSING as the state
write_frame complains that state is already CLOSING
Therefore, the problem is that `write_frame(OP_CLOSE, data)` gets called twice, or that it doesn't handle getting called twice

**Comment by aaugustin** [comment] 2018-04-13 19:29
Looks like I got my invariants wrong at some point :-(

async is hard, folks.

**Comment by aaugustin** [comment] 2018-04-29 16:42
I'm not managing to reproduce this problem :-/

@brianblakewong Could you try adding this at the beginning of the client.py and server.py scripts, reproduce the error, and paste the output here?

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

Thanks!

**Comment by aaugustin** [comment] 2018-05-06 20:15
To clarify my earlier comment about invariants: `websockets` is supposed to write a CLOSE frame only after checking that the connection state is OPEN and changing it to CLOSING, without yielding in the meantime. `write_frame` contains an assertion to enforce this.

The issue here is that `write_frame` runs after the state has changed to CLOSING. Based on the stack trace, I believe we're talking about this call to `write_frame`:

https://github.com/aaugustin/websockets/blob/9b0929582874cab3b3d18e283a841c43fd198eaf/websockets/protocol.py#L377-L390

Reading the implementation of `wait_for` in Python 3.6, I don't see how it could yield to the event loop before executing its first argument. I'm not seeing what else could explain the problem we're seeing.

Could you try applying this change and see it if makes the problem go away? That would help narrowing down the cause.

```diff
diff --git a/websockets/protocol.py b/websockets/protocol.py
index 541aa75..d6bcd01 100644
--- a/websockets/protocol.py
+++ b/websockets/protocol.py
@@ -378,16 +378,7 @@ class WebSocketCommonProtocol(asyncio.StreamReaderProtocol):
             # 7.1.2. Start the WebSocket Closing Handshake
             # 7.1.3. The WebSocket Closing Handshake is Started
             frame_data = serialize_close(code, reason)
-            try:
-                yield from asyncio.wait_for(
-                    self.write_frame(OP_CLOSE, frame_data),
-                    self.timeout, loop=self.loop)
-            except asyncio.TimeoutError:
-                # If the close frame cannot be sent because the send buffers
-                # are full, the closing handshake won't complete anyway.
-                # Cancel the data transfer task to shut down faster.
-                # Cancelling a task is idempotent.
-                self.transfer_data_task.cancel()
+            yield from self.write_frame(OP_CLOSE, frame_data)

         # If no close frame is received within the timeout, wait_for() cancels
         # the data transfer task and raises TimeoutError. Then transfer_data()
```

**Comment by CookiesBestDinner** [comment] 2018-05-07 23:00
Doesn't matter if it protects from interference from others, it **is** the interference

..right? It's the other call to `write_frame(OP_CLOSE)` that has yielded while in closing state (which presumably comes receiving CLOSE from the server)

(also, should it really be blocking?)

I had the same issue. Once, the first time I ran the example. Couldn't and can't reproduce.
I barely know what I'm saying here. I don't know websockets or asyncio. Just sharing what I do see for whatever that is worth.

**Comment by AnthonyBrunasso** [comment] 2018-05-15 18:26
@aaugustin I can repro this issue almost 100% of the time when I alter the client code to run 10 tasks on the event loop sending a name to the server.

Applying your diff fixes the issue.

**Comment by aaugustin** [comment] 2018-05-17 19:18
Thank you very much Anthony, I can reproduce the error with that script.

**Comment by aaugustin** [comment] 2018-05-17 19:54
Fun fact: activating DEBUG logs to diagnose the issue makes it go away...

However, with a few print statements, I see the following scenario:

1. `hello` exits the `async with websockets.connect` block, which calls `close`
2. `close` enters `yield from asyncio.wait_for(self.write_frame(OP_CLOSE, frame_data), ...)` and yields control to the event loop _before calling `write_frame`_ (which I didn't expect)
3. `transfer_data_task`, which is executing `read_data_frame`, receives a close frame from the server, calls `yield from self.write_frame(OP_CLOSE, frame.data)`, which completes successfully
4. the task started by `asyncio.wait_for` at step 2 resumes executing; at this point the state has changed to CLOSING; this results in the exception reported here.

So the issue is that `close` yields control to the event loope between `if self.state is State.OPEN` and `self.write_frame(OP_CLOSE, frame_data)`, making it possible for two coroutins to enter `self.write_frame(OP_CLOSE, frame_data)` simultaneously.

**Comment by aaugustin** [comment] 2018-05-17 20:44
I confirmed manually that the error no longer happens with Anthony's script with the changes in that PR.

**Closed** 2018-05-17 20:51 UTC
Labels: bug, has patch
