### ISSUE TITLE
Error in connection handler after code 1006 - unclear error reporting

### ISSUE THREAD

**Issue by chmedly** [aaugustin/websockets#624] opened 2019-06-21 18:36 UTC
While troubleshooting a client, my server code sometimes crashes.  This is what I get.  It's not clear to me if I'm causing this.  Sorry that I don't include any of my code but it would be very difficult to unwind it into a presentable block at the moment.  And it's not worth my time if this is unrelated...  
```
connection removed <websockets.server.WebSocketServerProtocol object at 0x75f09a70> : WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
Error in connection handler
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/websockets/protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "/home/pi/.local/lib/python3.7/site-packages/websockets/protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/home/pi/.local/lib/python3.7/site-packages/websockets/protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/home/pi/.local/lib/python3.7/site-packages/websockets/protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "/home/pi/.local/lib/python3.7/site-packages/websockets/framing.py", line 99, in read
    data = yield from reader(2)
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
concurrent.futures._base.CancelledError
```

**Comment by aaugustin** [comment] 2019-06-22 07:39
This could be a bug in websockets. I'll try to spend a bit more time to understand what could cause this.

**Comment by aaugustin** [comment] 2019-06-22 16:38
I think this is more or less intended, but perhaps there's room for improvement.

You're seeing this stack trace because the connection handler crashed. That's what `Error in connection handler` means.

When a connection handler raises an exception, the websockets server must handle it, or else it would crash entirely. So it logs the exception.

In this case, something went wrong; probably the connection died. An internal task managed by websockets got cancelled (specification, `transfer_data_task` was cancelled by `fail_connection()`). You were likely awaiting `recv()` and the cancellation propagated to your code.

This is where I'm wondering if there is room for improvement. Probably it would be better to raise a ConnectionClosed exception than a CancelledError. Cancellation shouldn't propagate outside of websockets internals.

**Comment by headrotor** [comment] 2019-06-26 19:41
Any chance of an example server with error handling? Having some basic issues with a hardware device that shuts down (for power saving) without properly closing client connection and I don't know how to deal with that on the server. I can catch it in task.result() but server seems to stop working after that.

**Comment by pystd** [comment] 2019-06-27 04:51
When call `connect()`,set the param `ping_interval=None`,seems to be able to solve.

**Comment by aaugustin** [comment] 2019-06-27 05:18
@headrotor It's going to be hard to help you just with the information you provided. Is a client on a server running on the device that shuts down? What behavior do you observe on the other end? What is `task` when you say "I can catch it in task.result()"? In what sens does the server "seems to stop working"?

**Comment by headrotor** [comment] 2019-06-27 16:52
Appreciate the response!

And apologies, my assumption here is I'm doing something wrong -- didn't mean to ask you to debug!  -- so examples of error handling would be very useful.  

The client is on an ESP32 module that shuts down so has no observable behavior. 
 Server code (very minimal) is here : https://github.com/headrotor/asyncio-esp 

I get error as in original post then server stops responding even without the "raise e".   Will run later with logging=DEBUG and see if that's more informative, but just wanted to know how to catch errors. Problem could very well be on client!

**Comment by aaugustin** [comment] 2019-06-27 19:09
OK, nothing comes to mind immediately...

If an exception occurs while your connection handler is managing the connection, it's logged at the ERROR level: https://github.com/aaugustin/websockets/blob/master/src/websockets/server.py#L195

Regardless of what happens on one connection, your server should accept other connections. Perhaps your server is making a blocking call that blocks the asyncio event loop?

**Comment by pystd** [comment] 2019-06-28 03:01
I think the reason is that the client did not receive a response from the server after issuing the ping command, and then the client actively disconnected.

**Comment by aaugustin** [comment] 2019-07-02 20:56
Going back to the first message in this discussion, the issue is unclear error reporting on the server side when the client closes the TCP connection without a proper closing handshake.

This is the same as #579 but on the other side of the connection.

**Closed** 2019-07-07 17:17 UTC
Labels: enhancement
