### ISSUE TITLE
Can't stop server correctly: "Task was destroyed but it is pending!"

### ISSUE THREAD

**Issue by andreymal** [aaugustin/websockets#64] opened 2015-08-06 22:39 UTC
If server has connected client (and waits `conn.recv()`), then Ctrl+C dont'close it, even if i call all closing functions:

```
server.close()
loop.run_until_complete(server.wait_closed())
loop.close()
```

I get this error:

```
Task was destroyed but it is pending!
task: <Task pending coro=<run() running at websockets/protocol.py:235> 
  wait_for=<Future pending cb=[Task._wakeup()]>
  cb=[_wait.<locals>._on_completion() at asyncio/tasks.py:399]>
Task was destroyed but it is pending!
task: <Task pending coro=<get() running at asyncio/queues.py:198> 
  wait_for=<Future pending cb=[Task._wakeup()]>
  cb=[_wait.<locals>._on_completion() at asyncio/tasks.py:399]>
Task was destroyed but it is pending!
task: <Task pending coro=<handler() running at websockets/server.py:64> 
  wait_for=<Future pending cb=[Task._wakeup()]>>
```

You can see [full server and client example with this problem](https://gist.github.com/zed/56f9bd5d33fff51f6820) by jfs or [simple server example](http://ru.stackoverflow.com/questions/433554) in my original question on ru.SO.

I'm doing something wrong or there really a bug?

**Comment by aaugustin** [comment] 2015-08-07 07:46
When you write "Ctrl+C dont'close it", do you mean that the server keeps running?
I can reproduce these warnings. The server terminates.

**Comment by andreymal** [comment] 2015-08-07 07:55
Yes, server terminates immediately with these warnings. But client returns close code 1006 instead 1000 or others, and i don't know how to close it properly with Ctrl+C.

**Comment by aaugustin** [comment] 2015-08-07 13:28
With the commit I just pushed, the client should get close code 1001, which is appropriate when the server goes away. Could you confirm that it solves your problem?

Thanks!

**Comment by andreymal** [comment] 2015-08-07 17:33
Yes, client closed properly with code 1001, it's good :)

But console has a new error text (i ran simple server from SO question):

```
Listen
client started
^Cclient finished
Task was destroyed but it is pending!
task: <Task pending coro=<handler() running at websockets/server.py:77> wait_for=<Future finished result=None>>
Finished
```

**Comment by aaugustin** [comment] 2015-08-07 21:04
Indeed... I don't know how I missed this...

**Comment by aaugustin** [comment] 2015-08-07 21:16
Now this should be fixed for real.

**Comment by andreymal** [comment] 2015-08-07 21:19
Yes, it works!

**Comment by andreymal** [comment] 2015-08-08 15:06
Hm, now if I set `logging.basicConfig(level=logging.INFO)`, i get it (with just one connected client):

```
Listen
client started
^CINFO:websockets.protocol:Failing the WebSocket connection: 1001 
INFO:websockets.protocol:Failing the WebSocket connection: 1006 
client finished
Finished
```

I'm not sure it's good

**Comment by aaugustin** [comment] 2015-08-08 22:05
Yes, I saw that as well. It happens because the connection is shut down before the server receives a close frame from the browser, as you can see by setting the log level to DEBUG:

    2015-08-08 23:59:17 Using selector: KqueueSelector
    2015-08-08 23:59:17 Listen
    2015-08-08 23:59:18 client started
    2015-08-08 23:59:18 server << Frame(fin=True, opcode=1, data=b'connected')
    2015-08-08 23:59:18 server >> Frame(fin=True, opcode=1, data=b'CONNECTED')
    2015-08-08 23:59:20 server << Frame(fin=True, opcode=1, data=b'x')
    2015-08-08 23:59:20 server >> Frame(fin=True, opcode=1, data=b'X')
    ^C2015-08-08 23:59:22 Failing the WebSocket connection: 1001 
    2015-08-08 23:59:22 server >> Frame(fin=True, opcode=8, data=b'\x03\xe9')
    2015-08-08 23:59:22 Failing the WebSocket connection: 1006 
    2015-08-08 23:59:22 client finished
    2015-08-08 23:59:22 Finished

Now I realize that the server should perform a regular closing handshake (and wait for the client's response) instead of a connection failure (where it closes the connection outright). I'll try to do that.

Thanks for your continued feedback! :-)

**Closed** 2015-08-09 20:07 UTC
