### ISSUE TITLE
Broadcasting same message to many clients

### ISSUE THREAD

**Issue by AmirHmZz** [aaugustin/websockets#931] opened 2021-04-24 22:54 UTC
When it comes to deployment in large scale , optimization becomes more important.
In some cases, websocket servers want to broadcast **one same message** to all connected clients repeatedly. Is there any way to do all necessary things with one message ( **framing** + **compressing** ) and just send the prepared message to many clients ? #932

**Comment by aaugustin** [comment] 2021-04-25 07:11
Currently websockets doesn't provide an API to do this.

This feature request comes up once in a while. Let's keep this issue open to track it.

**Comment by AmirHmZz** [comment] 2021-04-25 20:07
I've tried to add this feature in a PR,
Anyway, is there anyway to do this without this PR ?
I need `Frame.serialize()` method in `lagacy.framing.Frame` but it seems it's not accessible from outside of package.

**Comment by aaugustin** [comment] 2021-04-26 06:53
Currently, the entire logic for writing frames takes a couple dozen lines:

https://github.com/aaugustin/websockets/blob/dda3dfa992ddf6045be48c34143e4c1656dff9d4/src/websockets/legacy/protocol.py#L1078-L1091

https://github.com/aaugustin/websockets/blob/dda3dfa992ddf6045be48c34143e4c1656dff9d4/src/websockets/legacy/framing.py#L100-L124

If you're ready to use private APIs, you can do something like:

```python
frame = Frame(fin, Opcode(opcode), data)
data = frame.serialize(mask=mask, extensions=extensions)
for websocket in websockets:
    if websocket.state is State.OPEN:
        websockets.transport.write(data)
```

**Comment by aaugustin** [comment] 2021-04-26 06:55
Also, thanks for submitting a PR. I reviewed it; unfortunately I'm not convinced this is the best API for providing this functionality. I put a lot of focus on designing a nice API in websockets and it's hard to change later so I'd like to invest effort upfront to figure out the best possible solution.

**Comment by AmirHmZz** [comment] 2021-04-26 10:57
Thanks for your review and solution.
Of course I wanna try private apis , but the only problem is when I do something like :
```
from websockets.framing import Frame
Frame(True,0,b"").serialize()
```
I'll get an error :
`AttributeError: 'Frame' object has no attribute 'serialize'`
As I said it seems accessible `Frame` class from outside of package is [`websockets/frames.Frame`](https://github.com/aaugustin/websockets/blob/dda3dfa992ddf6045be48c34143e4c1656dff9d4/src/websockets/frames.py#L76) which doesn't have a method called `serialize()`. 
So how can I access the [`websockets/legacy/framing.Frame`](https://github.com/aaugustin/websockets/blob/dda3dfa992ddf6045be48c34143e4c1656dff9d4/src/websockets/legacy/framing.py#L26)?

**Comment by aaugustin** [comment] 2021-04-26 12:54
In the last public release (8.1) serializing and sending a frame is all done by the same function:

https://github.com/aaugustin/websockets/blob/139085fe2624192a5a6c72b1e5db211dcec6ced1/src/websockets/framing.py#L148-L216

You should run the code from the master branch until I make a release.

(Not great, but this discussion already went into unsupported territory some time ago...)

**Comment by aaugustin** [comment] 2021-05-02 20:45
This is actually a duplicate of #870.

**Closed by aaugustin** 2021-05-02 20:45 UTC
Labels: enhancement, low priority
