### ISSUE TITLE
TypeError("'<=' not supported between instances of 'int' and 'NoneType'",)

### ISSUE THREAD

**Issue by volodchenkov** [aaugustin/websockets#350] opened 2018-02-18 23:13 UTC
Hi!
I found a lot of errors in my log like:
```
2018-02-18 23:10:35,779 ERROR Task exception was never retrieved
future: <Task finished coro=<listen() done, defined at /opt/bet/src/server/websock/server.py:55> exception=TypeError("'<=' not supported between instances of 'int' and 'NoneType'",)>
Traceback (most recent call last):
  File "/opt/bet/src/server/websock/server.py", line 58, in listen
    msg = await websocket.recv()
  File "/opt/bet/env/lib/python3.6/site-packages/websockets/protocol.py", line 323, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
  File "/opt/bet/env/lib/python3.6/site-packages/websockets/exceptions.py", line 147, in init
    if 3000 <= code < 4000:
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

My code:
```python
while True:
    msg = await websocket.recv()
    logger.debug("Got message from %s: %s", token, msg)
```

I use nginx for proxy websockets with this config file:
```
    location /websocket/ {
        proxy_pass http://127.0.0.1:8033;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
```

**Comment by mattpepin** [comment] 2018-02-23 19:37
Confirmed, I have the same issue. It seems that in some cases, code can be None. It originates from the same stack trace in my case.

**Comment by aaugustin** [comment] 2018-03-01 20:15
Yes, I think this was reported before, it's a bug. I'm not sure how it happens exactly.

**Comment by BeatButton** [comment] 2018-03-08 18:38
It's very simple. `WebSocketCommonProtocol`'s init sets `close_code` to `None`, and the exception assumes it's an integer. The fix is trivial, as well, I can open a PR if you'd like.

**Comment by BeatButton** [comment] 2018-03-08 18:38
Oh, sorry, looking into it seems that `connection_lost` isn't always being called, since that sets the code to 1006

**Comment by bmoscon** [comment] 2018-03-24 11:32
yes please fix this. I can hit this repeatedly via this scenario:

context manager + async for to read messages from websocket:
eg: 
```
async for message in websocket:
            await handler(message)
```
and in a separate coroutine I `close` the websocket, the issue happens every time.

**Comment by bmoscon** [comment] 2018-03-24 12:12
here is a reproducible example/test case:

```
import asyncio

import websockets


ADDRESS = 'wss://echo.websocket.org'


async def kill(websocket):
    await asyncio.sleep(5)
    await websocket.close()


def main():
    asyncio.get_event_loop().run_until_complete(run())
       
def run():
    test = [asyncio.ensure_future(connect())]
    _, _ = yield from asyncio.wait(test)


async def connect():
    async with websockets.connect(ADDRESS) as websocket:
        asyncio.ensure_future(kill(websocket))
        async for message in websocket:
            await handler(message)

async def handler(message):
    await asyncio.sleep(10)
    print(message)

if __name__ == '__main__':
    main()
```


Once you run this, you must simulate a network issue (I turn off networking). After a few seconds I get the traceback each time:


```
Task exception was never retrieved
future: <Task finished coro=<connect() done, defined at test.py:22> exception=TypeError("'<=' not supported between instances of 'int' and 'NoneType'",)>
Traceback (most recent call last):
  File "test.py", line 25, in connect
    async for message in websocket:
  File "/home/bryant/websockets/websockets/py36/protocol.py", line 15, in __aiter__
    yield await self.recv()
  File "/home/bryant/websockets/websockets/protocol.py", line 323, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
  File "/home/bryant/websockets/websockets/exceptions.py", line 147, in __init__
    if 3000 <= code < 4000:
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

If I don't disconnect the network, there is no traceback/exception, so something about the network disconnect is responsible for this.

**Comment by ddehghan** [comment] 2018-04-12 06:40
At the time that bug hits using the test code of @bmoscon  the self.state = State.CLOSING

Maybe that is the problem. Since the connections is closing the close_code is not defined yet.

**Comment by aaugustin** [comment] 2018-05-02 19:26
Fixed in 402059e4a46a764632eba8a669f5b012f173ee7b.

**Closed by aaugustin** 2018-05-02 19:26 UTC
Labels: bug

**Comment by cjerdonek** [comment] 2018-05-02 20:02
Question: is `code` now allowed to be `None`, or did you limit the change to fixing what was causing it to be None?

**Comment by BeatButton** [comment] 2018-05-02 20:17
The latter. The code being ```None``` stemmed from an error in handling a force close.

**Comment by bmoscon** [comment] 2018-05-03 13:46
@aaugustin awesome! Thanks for fixing this. Any idea when a new release will be pushed to pypi?

**Comment by aaugustin** [comment] 2018-05-03 20:58
I'm planning to go through open issues over the next few weeks, fix what I can, and then make a release. There may be multiple backwards incompatible change that I'd like to group in the same major release.
