### ISSUE TITLE
Connection closed when server is slow to respond

### ISSUE THREAD

**Issue by gnachman** [aaugustin/websockets#604] opened 2019-04-24 07:01 UTC
I have a problem where a slow web server causes the client to throw an exception rather than wait for its response. This occurs after the client has sent its request but before the server responds with an HTTP status code.

The exception is thrown here:
```
Traceback (most recent call last):
  File "[elided]/websockets/client.py", line 90, in read_http_response
    status_code, headers = yield from read_response(self.reader)
  File "[elided]/websockets/http.py", line 122, in read_response
    status_line = yield from read_line(stream)
  File "[elided]/websockets/http.py", line 196, in read_line
    raise ValueError("Line without CRLF")
ValueError: Line without CRLF
```

The reason for the exception is that the stream has an eof condition. `stream.at_eof()` returns `true` at this point. So one minor issue is that this isn't actually a "Line without CRLF" but a premature EOF.

My real question is where this EOF comes from. After adding some logging I can see that `eof_received` in `protocol.py` gets called. I can't figure out why, though. I can't think of any reason why the timeout would have occurred at the TCP level. The connection is established, after all, since the server was able to read the request, and the client is connecting to localhost 
 so it's not like a packet was lost. I have disabled pings by passing `ping_interval=None` to `websockets.connect`. Is there some hidden source of timeouts in asyncio?

**Comment by aaugustin** [comment] 2019-04-25 15:55
Yes, the error message is misleading, that's #494.

Nothing comes to mind immediately... If this is a bug, then it should be fairly easy to reproduce with a server that waits for a very long time before answering the connection.

Is this a connection to localhost? On what OS are you seeing this?

**Comment by gnachman** [comment] 2019-04-27 03:55
I'm connecting to localhost on macOS.

**Comment by aaugustin** [comment] 2019-06-22 18:17
I've been trying to reproduce this. I'm also using macOS.

I'm running `nc -l 8765` in a console and `PYTHONPATH=src python example/client.py` in another.

I've been waiting for a very long time without seeing this error — except if I exit `nc`.

As far as I can tell, `eof_received` is triggered if `recv_into` returns 0 bytes: https://github.com/python/cpython/blob/9ffca670ed4df42eb256e7144619a9d3a830e7c0/Lib/asyncio/selector_events.py#L810-L822

`man 2 recv` says this happens if no messages are available to be received and the peer has performed an orderly shutdown.

As far as websockets is concerned, this looks like the remote endpoint is closing the TCP connection.

I'm going to close this issue because I don't see what else I could do but I'm happy to reopen if you can provide more information.

**Closed by aaugustin** 2019-06-22 18:17 UTC
