### ISSUE TITLE
A bug in python 3.7?

### ISSUE THREAD

**Issue by yjqiang** [aaugustin/websockets#432] opened 2018-07-04 03:51 UTC
cannot 'yield from' a coroutine object in a non-coroutine generaorator.

RuntimeWarning: coroutine "BaseEventLoop.create_ connection" was never awaited.

**Comment by yjqiang** [comment] 2018-07-04 03:53
try:
            self.ws = await websockets.connect('wss://broadcastlv.chat.bilibili.com/sub', timeout=3)
        except:
            print("# 连接无法建立，请检查本地网络状况")
            print(sys.exc_info()[0], sys.exc_info()[1])
            return False

**Comment by yjqiang** [comment] 2018-07-04 03:53
It works well in python 3.6, while crash in python 3.7.

**Comment by RemiCardona** [comment] 2018-07-04 05:40
Could you print the python backtrace here ? Thanks

**Comment by yjqiang** [comment] 2018-07-04 05:49
<class 'TypeError'> cannot 'yield from' a coroutine object in a non-coroutine generaorator.

(The code I showed before)RuntimeWarning: coroutine "BaseEventLoop.create_ connection" was never awaited.

**Comment by yjqiang** [comment] 2018-07-04 05:50
That is all it shows to me. But you can run the code I gave, and print more information.

**Comment by yjqiang** [comment] 2018-07-04 05:53
https://github.com/yjqiang/bilibili-live-tools/blob/master/bilibiliCilent.py


https://github.com/yjqiang/bilibili-live-tools/blob/master/connect.py


These are the concrete codes

**Comment by RemiCardona** [comment] 2018-07-04 05:53
You're hiding the backtrace, please remove the `try`/`except` and let the full backtrace print on screen, and copy paste that. Thanks

**Comment by yjqiang** [comment] 2018-07-04 06:33
Traceback (most recent call last):
  File "0.py(1).py", line 15, in <module>
    loop.run_until_complete(run())
  File "D:\Python\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "0.py(1).py", line 7, in run
    ws = await websockets.connect('wss://broadcastlv.chat.bilibili.com/sub', timeout=3)
  File "D:\Python\lib\site-packages\websockets\client.py", line 397, in __await__
    transport, protocol = yield from self._creating_connection
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
sys:1: RuntimeWarning: coroutine 'BaseEventLoop.create_connection' was never awaited

**Comment by RemiCardona** [comment] 2018-07-04 06:59
Dupe of #405 then. 3.7 is supported on master - which I encourage you to test - and the next release will include the necessary changes. Closing. Thanks

**Closed by RemiCardona** 2018-07-04 06:59 UTC

**Comment by yjqiang** [comment] 2018-07-04 07:44
I noticed that once, but couldn't find in a short time, so I thought it is the feature for python3.8. LOL. Anyway thanks a lot.

**Comment by aaugustin** [comment] 2018-07-16 19:55
Version 6.0 adds support for Python 3.7 and is now available on PyPI: https://pypi.org/project/websockets/6.0/#files
