### ISSUE TITLE
Anyio integration (Trio support)

### ISSUE THREAD

**Issue by uSpike** [aaugustin/websockets#969] opened 2021-05-23 16:16 UTC
To my knowledge, there doesn't currently exist a high-quality websocket library that can support multiple I/O back-ends such as asyncio and trio.  Given the Sans-IO nature of this library, there's an opportunity to leverage the [anyio](https://anyio.readthedocs.io/en/stable/) library to support asyncio and trio with one implementation.  It would also open the door for other back-ends which may be supported by anyio in the future, such as twisted.

https://github.com/miracle2k/trio-websockets might be a decent reference for this, since it is a version of this library ported to Trio, which is very similar to Anyio.

**Comment by aaugustin** [comment] 2021-05-23 18:40
Thanks for bringing up these projects; I wasn't aware of them!

I've been meaning to write a Trio version of websockets but I haven't started yet. Using the native patterns of Trio would be an important design goal. I'd have to see how anyio fares in this area. If it attempts to make Trio look like asyncio, probably that won't meet my design goals.

**Comment by uSpike** [comment] 2021-05-23 21:31
@aaugustin thanks for the response.  Anyio uses Trio principles and is as close to the Trio API as possible, while (amazingly) working with an asyncio back-end as well.  Anyio supports all of the structured concurrency concepts needed to write a library like task groups, cancellation scopes, thread execution, etc.  Check it out!

**Comment by belm0** [comment] 2021-05-24 04:43
> I've been meaning to write a Trio version of websockets but I haven't started yet

It would be effectively reimplementing https://github.com/HyperionGray/trio-websocket -- is there something specifically wrong with that existing library?

And since trio-websocket is already on Trio, already has an API that considers cancel scopes and structured concurrency, porting to anyio would be straightforward.

**Comment by aaugustin** [comment] 2021-05-24 05:30
I'm writing websockets for fun. Some people do crosswords; I do open source software. There's nothing wrong with solving a puzzle someone else solved before :-)

**Comment by belm0** [comment] 2021-05-24 07:10
> I'm writing websockets for fun. Some people do crosswords; I do open source software. There's nothing wrong with solving a puzzle someone else solved before :-)

Totally fine in and of itself, but the picture changes when 3rd party users of the software are involved.  From the user's perspective, they'd rather have otherwise competing developers cooperate on a single high quality library [*], and not have to chose between two options in the first place.  (Half will make the wrong choice in this game.)

[*] doubly so given the relatively tiny worlds of asyncio, trio, and anyio

**Comment by aaugustin** [comment] 2021-05-24 09:55
> they'd rather have otherwise competing developers cooperate on a single high quality library

That's true.

Unfortunately, several other Python projects related to WebSocket started after websockets gained traction, leading to fragmentation.

**Comment by belm0** [comment] 2021-06-02 12:21
> A few years ago websockets got right some minor details that wsproto got wrong, but I believe wsproto catched up recently, perhaps thanks to new maintainers, so this isn't a concern anymore.

wsproto does have its problems.  I reported a significant performance regression last year, the maintainers don't seem concerned.

https://github.com/python-hyper/wsproto/issues/152

**Comment by aaugustin** [comment] 2021-06-05 20:59
I learnt about anyio (among other things) thanks to this issue, so I'm happy we had this discussion. However, at this point, I'm not seeing any action to be taken, so I'm going to close it.

Rationale:

- websockets already provides an asyncio implementation
- I'm planning to redo it on top of websockets' Sans-I/O layer; depending on asyncio is hard enough in itself; I don't want to increase complexity with an intermediary layer (especially one that attemps to masquerade asyncio as trio — some abstractions are going to be leaking — there's already quite a bit of leaking in asyncio)

- other projects already provide a trio implementation
- I'm planning to create one on top of websockets', but given the above, the only benefit of anyio is "maybe it'll add support for other backends"; this benefit feels rather speculative vs. the cost of adding a dependency

**Closed by aaugustin** 2021-06-05 20:59 UTC

**Comment by aaugustin** [comment] 2026-07-29 17:41
Trio support is now released.
