### ISSUE TITLE
Decompression module

### ISSUE THREAD

**Issue by slavaromanov** [aaugustin/websockets#158] opened 2017-02-01 20:17 UTC
I was faced with the problem in framing module.
Function in read_frame checking RSVs states, but it do not consider that the RSV1 is compression bit 
[RFC 7692](https://tools.ietf.org/html/rfc7692)

This code solved my problem with deflate decompression.
But it has no support dynamic "client_max_window_bits" (in my example it 15). 

[framing.py](https://github.com/aaugustin/websockets/blob/master/websockets/framing.py)
```python
@asyncio.coroutine
def read_frame(reader, mask, *, max_size=None):
    """
    Read a WebSocket frame and return a :class:`Frame` object.

    ``reader`` is a coroutine taking an integer argument and reading exactly
    this number of bytes, unless the end of file is reached.

    ``mask`` is a :class:`bool` telling whether the frame should be masked
    i.e. whether the read happens on the server side.

    If ``max_size`` is set and the payload exceeds this size in bytes,
    :exc:`~websockets.exceptions.PayloadTooBig` is raised.

    This function validates the frame before returning it and raises
    :exc:`~websockets.exceptions.WebSocketProtocolError` if it contains
    incorrect values.

    """
    # Read the header
    data = yield from reader(2)
    head1, head2 = struct.unpack('!BB', data)
    fin = bool(head1 & 0b10000000)
    decompressor = None
    if head1 & 0b01110000:
        if head1 & 0b00110000:
            raise WebSocketProtocolError("Reserved bits must be 0")
        else:
            decompressor = zlib.decompressobj(-15)
    opcode = head1 & 0b00001111
    if bool(head2 & 0b10000000) != mask:
        raise WebSocketProtocolError("Incorrect masking")
    length = head2 & 0b01111111
    if length == 126:
        data = yield from reader(2)
        length, = struct.unpack('!H', data)
    elif length == 127:
        data = yield from reader(8)
        length, = struct.unpack('!Q', data)
    if max_size is not None and length > max_size:
        raise PayloadTooBig("Payload exceeds limit "
                            "({} > {} bytes)".format(length, max_size))
    if mask:
        mask_bits = yield from reader(4)

    # Read the data
    data = yield from reader(length)
    if decompressor:
        data = decompressor.decompress(data)
    if mask:
        data = bytes(b ^ mask_bits[i % 4] for i, b in enumerate(data))
    frame = Frame(fin, opcode, data)
    check_frame(frame)
    return frame
```

**Comment by aaugustin** [comment] 2017-02-02 08:14
I think this is covered by https://github.com/aaugustin/websockets/issues/93.

I'd like to provide proper APIs for supporting extensions, not just to hardcode this one in the middle of the protocol implementation.

**Comment by aaugustin** [comment] 2017-05-03 19:25
Closing a a duplicate of #93. See also #178.

**Closed by aaugustin** 2017-05-03 19:25 UTC
