### ISSUE TITLE
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x7f25014d3810>; the handler is closed

### ISSUE THREAD

**Issue by garima-trivedi** [aaugustin/websockets#1138] opened 2022-03-03 17:03 UTC
After upgrading to websockets==10.2 (latest uvicorn release 0.17.5)

It seems something changed here: https://github.com/aaugustin/websockets/commit/f605e86aeab7ac045c21e2eac0d677916031022e related to closing the connection, and the line numbers in my sentry reports agree.
uvicorn.error:244 closing handshake failed

Traceback (most recent call last):

  File "/home/appuser/.local/lib/python3.9/site-packages/websockets/legacy/server.py", line 240, in handler
    await self.close()
  File "/home/appuser/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 779, in close
    await asyncio.shield(self.close_connection_task)
  File "/home/appuser/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1312, in close_connection
    self.transport.write_eof()
  File "uvloop/handles/stream.pyx", line 696, in uvloop.loop.UVStream.write_eof
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x55f7ecebc570>; the handler is closed

I'm not sure if websockets library or uvicorn is the culprit here ?

**Comment by rslinckx** [comment] 2022-03-04 12:56
Can confirm that reverting to 10.1 fixes the issue for us with the latest uvicorn release

**Comment by Catastropha** [comment] 2022-03-09 21:47
Yes, this same issue was fixed with 10.1
Now it's reintroduced with 10.2

**Comment by ngnpope** [comment] 2022-04-04 18:58
This is a duplicate of #1072.

**Closed** 2022-04-17 11:27 UTC
Labels: bug
