### ISSUE TITLE
Common pattern for reconnections

### ISSUE THREAD

**Issue by pgrandinetti** [aaugustin/websockets#414] opened 2018-05-25 07:58 UTC
In several projects of mines I do something like the following, in order to handle scenario that may happen with connection errors and reconnection attempts:

```
    async def listen_forever(self):
        while True:
        # outer loop restarted every time the connection fails
            try:
                async with websockets.connect(self.url) as ws:
                    while True:
                    # listener loop
                        try:
                            reply = await asyncio.wait_for(ws.recv(), timeout=***)
                        except (asyncio.TimeoutError, websockets.exceptions.ConnectionClosed):
                            try:
                                pong = await ws.ping()
                                await asyncio.wait_for(pong, timeout=self.ping_timeout)
                                logger.debug('Ping OK, keeping connection alive...')
                                continue
                            except:
                                await asyncio.sleep(self.sleep_time)
                                break  # inner loop
                        # do stuff with reply object
            except socket.gaierror:
                # log something
                continue
            except ConnectionRefusedError:
                # log something else
                continue
```

and I was wondering whether (1) this makes sense at all, and (2) there is any shortcut already provided in `websockets` to what seems quite a recurrent behavior (assuming that is correct!)

**Comment by loganathan-s** [comment] 2019-09-20 13:22
any progress on this?

**Comment by aaugustin** [comment] 2019-09-20 13:26
no progress

**Comment by pgrandinetti** [comment] 2019-10-02 09:46
just saw the help wanted tag.
As I mentioned 1.5 years ago (!) I did use that piece of code in a couple of projects. I can help, but would need guidance.

**Comment by heckad** [comment] 2019-12-05 08:30
What needs to do to add this feature?

**Comment by aaugustin** [comment] 2019-12-05 13:01
For this feature, I would suggest:

- first, a documentation patch describing how the feature would behave exactly;
- once we agree on that, an implementation with tests.

**Comment by pgrandinetti** [comment] 2019-12-07 15:09
@heckad I placed a minimal reproducible example here, to start with: https://gist.github.com/pgrandinetti/964747a9f2464e576b8c6725da12c1eb

**Comment by heckad** [comment] 2019-12-07 21:24
I suggest doing like in aio_pika `connect_robust` method which should return `RobustConnection` or `RobustSomethingAnyThing` which will reconnect on any error by default. Another way make like in [requests](https://stackoverflow.com/questions/15431044/can-i-set-max-retries-for-requests-request).

**Comment by filwaline** [comment] 2020-10-31 09:04
Here is my attempt to talk with websocket server
Involved async-generator

```
import websockets

class WebSocketRetry:
    
    def __init__(self, uri):
        """
        IF __INIT__ WAS CALLED DIRECTLY
        THEN GENERATOR MUST SETUP MANUALLY 
        """
        self.client = self.get_websocket_connection(uri)
        self._flag_closed = False
        self._flag_inited = False
        
    @property
    def closed(self):
        return self._flag_closed
    
    @classmethod
    async def create(cls, uri):
        self = cls(uri)
        await self.client.asend(None)
        return self
    
    async def get_websocket_connection(self, uri):
        while not self.closed:
            try:
                print("Create New Connection...")
                async with websockets.connect(uri) as wb:
                    self._websocket = wb
                    
                    if not self._flag_inited:
                        self._flag_inited = True
                        data = yield
                        
                    while True:
                        await wb.send(data)
                        data = yield await wb.recv()

            except Exception as e:
                # todo 
                print(e)
                data = yield
                
    async def send(self, data):
        if self.closed:
            return await self._websocket.recv()
        return await self.client.asend(data)
    
    async def close(self):
        if not self.closed: 
            self._flag_closed = True
            await self._websocket.close()
```

Usage
```
In []: client = await WebSocketRetry.create("ws://localhost/echo")
Create New Connection...

In []: await client.send("hello")
Out[]: 'ECHO: hello'

In []: await client.send("hi")
Out[]: 'ECHO: hi'

In []: await client.close()

In []: await client.send("hi?")
#  ConnectionClosedError will raise
```

**Comment by aaugustin** [comment] 2021-05-02 20:17
An interesting API would be:

```python
async for ws in websockets.connect(...):
    ...
```

Now the question is: should it reconnect only on connection errors? on or all exceptions?

This isn't an easy question:

- reconnecting on connection errors seems legitimate while swallowing all exceptions is a Gun Pointed At Feet
- it seems Quite Hard to tell connection errors apart from other errors with a high degree of certainty

Also, we need exponential backoff to avoid going in a hot loop if the network or the server is down

**Comment by MelchiSalins** [comment] 2021-05-13 05:33
Could the behaviour of the reconnection be a parameter passed to the connect method? 

```python
async for ws in WebSockets.connect(reconnect_policy=websokets.ALWAYS, exponential_backoff=true):
         ...```

or something similar? Just putting it out there.

**Comment by adriansev** [comment] 2021-05-13 09:05
Just a small remark: re-connecting, and retry connecting are different things
*  the former assumes a successful initial connection that was dropped (so, the configuration is correct but a connection problem occurred so let's reconnect )
* the latter would be when no connection was successful, so let's keep trying to do so
IMHO, i would say that if session state (THIS_WAS_SUCCESSFUL) can be kept, then always (configurable) retry when there was an initial successful connection and always bailout if no initial connection

I think that this would translate to always retry if ConnectionClosedError and bailout in all other cases.. I'm not sure if there are cases where the session is valid but the connection was closed with ConnectionClosedOK

**Comment by aaugustin** [comment] 2021-06-05 10:02
Hello! I have a proposal here: #983. Sorry it took me so long to figure it out.

There's a wide variety of situations where connections can fail and require reconnecting. I don't have a good way to reproduce them all.

If you have a real life use case and you're able to test this pull request, I would be very interested in your feedback.

The idea would be to run the version of websockets from #983, to replace your reconnection system by:

```python
async for ws in websockets.connect(...):
    ...
```

Then you can check if the reconnection works. Errors that trigger reconnections are logged; if you see errors in the logs and the connection is still alive, you're good.

Looking forwards to your feedback. Thank you!

**Comment by aaugustin** [comment] 2021-06-05 10:02
@adriansev: you have a good point; indeed there's a different reasoning for errors opening the connections and errors after it's open.

Here's what I ended up doing:

- Errors opening the connection: retry with exponential backoff and no limit. I don't think depending on an initial successful connection is a good idea. For example, if the network or the server is momentarily down while a script starts, it makes sense to keep trying until the connection eventually works.
- Errors after the connection is open: I'm logging ConnectionClosed at the debug level (because you're expecting it, else you wouldn't be reconnecting in the first place) and other exceptions at the error level.

**Comment by aaugustin** [comment] 2021-06-09 05:56
I merged the branch but I'm still interested in feedback if you try it :-)

**Closed** 2021-06-09 05:55 UTC
Labels: enhancement, high priority

**Comment by adriansev** [comment] 2021-06-10 17:26
@aaugustin thank you for your work!! So, just to throw a disclaimer: my view is just from the point of view of the client (and a very dumb client, is a REPL interface to a server, so only one message at a time). So, my comments were from this view, and, as such, i continue to think that retrying the connection when no initial connection was done is pointless (maybe my certificate is wrong, or the wireless is disconnected so, i will wait for an answer from the server when in fact there are re-connecting tryouts in the websocket part). IMHO re-connect would be useful for cases when because of load and network a connection is dropped for very short time. So, for me, my fear is that this would convert to user reports like "i started the client, and nothing happens" as opposed to the often "error was thrown, look in the log" and in the end the problem was of certificate permission, mixed certificate and key (new with old) or other pure ssl problems that will threw errors at connection time.
So, i would say that that my use-case is really specific and unique and  my opinion does not matter on this...
The only thing that would simplify my code would be if an automatic re-connection at pong timeout and for an exception in send .. just FYI at this moment i do this: https://github.com/adriansev/jalien_py/blob/master/alienpy/alien.py#L514
But, in the end, i just thank you so much for your work! :)

**Comment by adriansev** [comment] 2021-06-10 22:15
Well, all depends on "is it worth it?" (in regard to discrimination of types of error and handle them differently) and the range of needs can be quite wide. but, as you say, it throws an exception so it's ok ...
About starting from scratch, well, there could be a knowledge delta in a week frame, in a year time one can be at the 3rd rewrite of the project :)))
But now that you threw the bait with the "elegant" could you please elaborate what would that mean? :)    
Also, i do not re-connect on pong (as i cannot know if an underlying ping failed to receive the pong.. that would need an separate thread, or in the same thread/task as ping/pong mechanism to have an callback for re-connection), i only do a re-connection when getting an exception from send
Thank you!

**Comment by aaugustin** [comment] 2021-06-13 13:43
By "elegant" I meant "can you do everything within a context manager" vs. having a global instance of the websockets client and reinitializing it when it fails.

The benefits are those of context managers -- generally they improve the structure of the code and give more clarity to which resource is used where.

**Comment by adriansev** [comment] 2021-06-13 16:53
ooh, yeah, that is excluded in my case, as in "technically impossible" : there is not possible to mix async with non-async modules/functions  .. so to solve my conundrum, actually i have a thread with the async main loop and a decorator to "un-syncify" the send/receive function (and a few other function that use directly the websocket)

**Comment by aaugustin** [comment] 2021-06-13 19:06
OK. You need #885, then!

**Comment by akhtarshahnawaz** [comment] 2021-10-04 17:52
```
def run():
    try:
        asyncio.get_event_loop().run_until_complete(call_api(json.dumps(msg)))
    except Exception as e:
        print(f'WEBSOCKET CONNECTION CLOSED. RESTARTING..', e)
        time.sleep(2)
        run()

run()

```

**Comment by coccoinomane** [comment] 2023-06-15 12:03
Thanks @aaugustin!  
For those stumbling on the broken documentation link, here's a working one:
https://websockets.readthedocs.io/en/stable/reference/asyncio/client.html#opening-a-connection

The solution is to do:

```python
async for websocket in websockets.connect(...):
    try:
        ...
    except websockets.ConnectionClosed:
        continue
```
