### ISSUE TITLE
socket.send() raised exception

### ISSUE THREAD

**Issue by neuroid** [aaugustin/websockets#84] opened 2015-12-05 21:42 UTC
Hi,

I have an issue with running a simple example (paraphrased from https://websockets.readthedocs.org/en/stable/intro.html). I'm testing with Python 3.4.2 (Debian Jessie default) and websockets from master. Consider the following code:

```python
# server.py
import asyncio
import websockets

@asyncio.coroutine
def send(websocket, path):
    while True:
        if not websocket.open:
            return
        yield from websocket.send('message')

start_server = websockets.serve(send, 'localhost', 8765)
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

```python
# client.py
import asyncio
import websockets

@asyncio.coroutine
def recv(uri):
    websocket = yield from websockets.connect(uri)
    while True:
        message = yield from websocket.recv()
        print(message)

asyncio.get_event_loop().run_until_complete(recv('ws://localhost:8765'))
```

I run `python server.py` in one terminal and `python client.py` in another. After I `^C` the client, the server starts printing `socket.send() raised exception.` and does not accept new connections.

After I `^C` the server I get the following output:

```python
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised ex^C
Traceback (most recent call last):
  File "server.py", line 13, in <module>
    asyncio.get_event_loop().run_forever()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 244, in run_forever
    self._run_once()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 1081, in _run_once
    handle._run()
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 291, in _wakeup
    self._step(value, None)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 235, in _step
    result = coro.send(value)
  File "/env/lib/python3.4/site-packages/websockets/server.py", line 77, in handler
    yield from self.ws_handler(self, path)
  File "server.py", line 9, in send
    yield from websocket.send('message')
  File "/env/lib/python3.4/site-packages/websockets/protocol.py", line 261, in send
    yield from self.write_frame(opcode, data)
  File "/env/lib/python3.4/site-packages/websockets/protocol.py", line 430, in write_frame
    write_frame(frame, self.writer.write, is_masked)
  File "/env/lib/python3.4/site-packages/websockets/framing.py", line 149, in write_frame
    writer(output.getvalue())
  File "/usr/lib/python3.4/asyncio/streams.py", line 269, in write
    self._transport.write(data)
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 613, in write
    logger.warning('socket.send() raised exception.')
  File "/usr/lib/python3.4/logging/__init__.py", line 1286, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.4/logging/__init__.py", line 1409, in _log
    self.handle(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 1419, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 1489, in callHandlers
    lastResort.handle(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 853, in handle
    self.emit(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 981, in emit
    stream.write(self.terminator)
KeyboardInterrupt
--- Logging error ---
Traceback (most recent call last):
--- Logging error ---
Traceback (most recent call last):
Exception ignored in: <bound method Task.__del__ of <Task finished coro=<handler() done, defined at /env/lib/python3.4/site-packages/websockets/server.py:54> exception=KeyboardInterrupt()>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 93, in __del__
  File "/usr/lib/python3.4/asyncio/futures.py", line 218, in __del__
  File "/usr/lib/python3.4/asyncio/base_events.py", line 950, in call_exception_handler
  File "/usr/lib/python3.4/logging/__init__.py", line 1303, in error
  File "/usr/lib/python3.4/logging/__init__.py", line 1409, in _log
  File "/usr/lib/python3.4/logging/__init__.py", line 1419, in handle
  File "/usr/lib/python3.4/logging/__init__.py", line 1489, in callHandlers
  File "/usr/lib/python3.4/logging/__init__.py", line 853, in handle
  File "/usr/lib/python3.4/logging/__init__.py", line 984, in emit
  File "/usr/lib/python3.4/logging/__init__.py", line 906, in handleError
  File "/usr/lib/python3.4/traceback.py", line 169, in print_exception
  File "/usr/lib/python3.4/traceback.py", line 153, in _format_exception_iter
  File "/usr/lib/python3.4/traceback.py", line 18, in _format_list_iter
  File "/usr/lib/python3.4/traceback.py", line 65, in _extract_tb_or_stack_iter
  File "/env/lib/python3.4/linecache.py", line 15, in getline
  File "/env/lib/python3.4/linecache.py", line 41, in getlines
  File "/env/lib/python3.4/linecache.py", line 126, in updatecache
  File "/env/lib/python3.4/tokenize.py", line 437, in open
AttributeError: 'module' object has no attribute 'open'
Task was destroyed but it is pending!
task: <Task pending coro=<run() running at /env/lib/python3.4/site-packages/websockets/protocol.py:299> wait_for=<Future finished result=True>>
```

Is this an expected behaviour? Perhaps there is some additional error handling required in my code?

**Comment by aaugustin** [comment] 2015-12-05 22:00
This looks like #23, but it's fixed in master, and #54, but we didn't reach a conclusion.

When you ^C the client, the TCP connection is terminated. I expect asyncio to call [connection_lost](https://github.com/aaugustin/websockets/blob/fd33d297d836bf0acf22b793450be0bd00e9e391/websockets/protocol.py#L514-L516). At that point [websocket.open](https://github.com/aaugustin/websockets/blob/fd33d297d836bf0acf22b793450be0bd00e9e391/websockets/protocol.py#L169-L175) must return False.

Can you do a bit of debugging and to confirm whether `connection_lost` gets called on the server when you ^C the client? In that case it colud be a bug in asyncio...

**Comment by neuroid** [comment] 2015-12-05 22:58
I can confirm that `connection_lost` is NOT getting called.

I also tested this example with Python 3.4.3 and 3.5.0. Same results.

**Comment by neuroid** [comment] 2015-12-05 23:20
Interestingly, if I add `yield from asyncio.sleep(0)` after the `websocket.send` call the problem goes away.

**Comment by SzieberthAdam** [comment] 2015-12-06 21:17
Hi!

It seems that killing the client ends up a `transport._fatal_error()` call which in turn (since this case the exception is `ConnectionResetError`) goes to `transport._force_close()`. This method makes a `loop.call_soon(self._call_connection_lost, exc)`. That method would tear down the transport properly if it would ever get called. However, the handler keeps pushing the writes and they all get scheduled ahead of that call. The `yield from asyncio.sleep(0)` you mentioned let the scheduler a small breath to deal with other scheduled stuff, including the tear down of the transport.

Another way to close the handler (instead of checking `websocket.open`) is:

    if websocket.writer.transport._conn_lost:
        return

I also found a reference to this ugly workaround on SO: http://stackoverflow.com/a/33979309/2334951
Well, it is ugly because it bugs with a private property.

Both way, the server still tries to do the closing handshake after the handler returns for no reason since the connection is lost.

**Comment by SzieberthAdam** [comment] 2015-12-07 12:18
Well, this seems to be an `asyncio` issue to me. The following server/client code produces the same behavior:

```
# server.py
import asyncio

import sys
import logging
loghandler = logging.StreamHandler(sys.stdout)
logging.basicConfig(level=logging.DEBUG, handlers=[loghandler])
loop = asyncio.get_event_loop()
loop.set_debug(True)


def client_connected_cb(client_reader, client_writer):
  n = 0
  while True:
    msg = str(n).encode() + b'\n'
    client_writer.write(msg)
    n += 1
    #if client_writer.transport._conn_lost:
    #  break


coro = asyncio.start_server(client_connected_cb,
  host='localhost', port=8765, loop=loop)

server = loop.run_until_complete(coro)
loop.run_forever()
```
```
# client.py
import asyncio

import sys
import logging
loghandler = logging.StreamHandler(sys.stdout)
logging.basicConfig(level=logging.DEBUG, handlers=[loghandler])
loop = asyncio.get_event_loop()
loop.set_debug(True)

async def client():
    reader, writer = await asyncio.open_connection(host='localhost', port=8765,
      loop=loop)
    while True:
      msg = (await reader.readline()).strip()
      if not msg:
        break
      else:
        n = int(msg.decode())
        print(n)
        if n >= 1000:
          break

loop.run_until_complete(client())
```

Make sure to kill the server shortly after starting the client to be able to read the server log.

Well, I would expect a `ConnectionResetError` exception at `client_writer.write(msg)`. However that exception is not thrown but is intended to be handled and should be obtainable in `client_reader.exception()`. If the `_call_connection_lost` method would ever get called the `while True:` loop could be replaced with `while not client_reader.exception():` or the existence of the exception could be tested inside to break from it. I would still prefer to face an explicit exception by calling the write but still this could be a way to handle the situation.

Unfortunately, `loop.call_soon` prevents us to do it. I replaced `self._loop.call_soon(self._call_connection_lost, exc)` with `self._call_connection_lost(exc)` in `asyncio/proactor_events.py` and it worked.

Moreover, it worked with Łukasz's example instantly since that way `protocol.connection_lost()` gets called immedately after the failed write by the `asyncio` mechanism.

Even if the connection is known to get lost, the `write_frame()` coro tries to drain the writer just to acknowledge that fact again and drive the `protocol.fail_connection()` coro with code 1006. Here, having both `protocol.connection_lost()` and `protocol.fail_connection()` to handle almost the same stuff seems redundant to me.

I report this issue on the Python issue tracker.

**Comment by aaugustin** [comment] 2015-12-07 12:52
Thanks for the great investigation, Ádám!

Let's see what the Python or asyncio maintainers say before considering a workaround.

**Comment by SzieberthAdam** [comment] 2015-12-07 17:15
Latest asyncio code fixes most part of the issue and raises a `ConnectionResetError` exception at the failed writer drain in `protocol.write_frame()`.

This is the server log with newest `asyncio` code.

```
DEBUG:websockets.protocol:server >> Frame(fin=True, opcode=1, data=b'message')
DEBUG:websockets.protocol:server >> Frame(fin=True, opcode=1, data=b'message')
DEBUG:websockets.protocol:server >> Frame(fin=True, opcode=1, data=b'message')
DEBUG:websockets.protocol:server >> Frame(fin=True, opcode=1, data=b'message')
DEBUG:asyncio:<_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>: Fatal write error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 702, in write
    n = self._sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
WARNING:asyncio:Executing <Task pending coro=<WebSocketServerProtocol.handler() running at /home/adam/fumbblplus/lib/python3.5/site-packages/websockets/server.py:77> created at /home/adam/fumbblplus/lib/python3.5/site-packages/websockets/server.py:52> took 1.435 seconds
INFO:websockets.protocol:Failing the WebSocket connection: 1006 
INFO:websockets.protocol:Failing the WebSocket connection: 1011 
INFO:websockets.server:Exception in closing handshake: [Errno 104] Connection reset by peer
```

It seems that the thrown `ConnectionResetError` also resulted an unexpected error (1011) in `protocol.run()`, and the protocol tries to do the closing handshake for no reason.

**Comment by aaugustin** [comment] 2015-12-07 17:36
This sounds more manageable already; at least the connection dies.

We should try to reproduce this with a unit test rather than a test script.

I'm pretty sure there are protocol tests that could be adjusted to reproduce this.

**Comment by aaugustin** [comment] 2015-12-12 11:23
@neuroid Are you able to test whether #85 resolves this issue for you? It does for me.

**Comment by neuroid** [comment] 2015-12-12 16:45
Yes, this fixes the problem.

**Comment by neuroid** [comment] 2015-12-12 16:54
As a side note, I'm unable to connect multiple clients at the same time to the example server I provided. Unless I add `yield from asyncio.sleep(0)` as before.

**Comment by aaugustin** [comment] 2015-12-12 17:08
You're running a busy `while True` loop. I don't think that's a realistic use case for the library.

**Comment by neuroid** [comment] 2015-12-12 17:09
Yes, I thought as much.

**Comment by aaugustin** [comment] 2015-12-12 17:57
Fixed in #85.

**Closed by aaugustin** 2015-12-12 17:57 UTC

**Comment by Ruined1** [comment] 2019-04-22 16:21
How do you catch this exception? `try:` doesn't catch it because it's not an exception. I know for my application I simply need to reconnect so I'd like to call my login function again but I can't find a way to catch `socket.send() raised exception.`

**Comment by aaugustin** [comment] 2019-04-22 19:21
You catch `websockets.ConnectionClosed` where you're interacting with websockets.

If websockets internals throw exceptions, that's a bug, which is why this was an issue.

**Comment by hs79hs** [comment] 2021-01-20 11:05
> You catch `websockets.ConnectionClosed` where you're interacting with websockets.
> 
> If websockets internals throw exceptions, that's a bug, which is why this was an issue.

Sorry, I'm not sure how to catch `websockets.ConnectionClosed` exception for `await websocket.send()`? It always return None.

Or how to know the current status of websocket before calling `await websocket.send()`? Thanks.

**Comment by aaugustin** [comment] 2021-01-20 14:00
```python
try:
    await websocket.send(...)
except websockets.ConnectionClosed:
    ... # handle exception
```

**Comment by hs79hs** [comment] 2021-01-21 02:03
Thank you, and yes, it's all my fault. In my project, at first it won't throw `websockets.ConnectionClosed` exception and `websocket.open` will always be `True` with `websocket.closed` always `False`, only print out
```
socket.send() raised exception.
```
every time when calling `ws.send(...)`

After debug, I have to add `await asyncio.sleep(0)` after `websocket.send(...)`, then all works like expected. So I think it's because the thread having `ws.send(...)` took all cpu time and websocket status never got changed.
