### ISSUE TITLE
Asyncio error and close timeout on ping abort when closing connection

### ISSUE THREAD

**Issue by BenjaminHamon** [aaugustin/websockets#669] opened 2019-09-03 19:40 UTC
Using websockets 8.0.2, python 3.7.2 on Windows 7.

When sending a ping over a closing connection, the ping gets aborted. On the sender side, asyncio logs an error `Future exception was never retrieved` for `ConnectionClosedOK`. On the receiver side, the connection is lost with code 1006 and returns after some time, which appears to be a close timeout.

Waiting for the pong appears to fix the asyncio error, but the websockets documentation states waiting for the pong is optional.

See the logs and test scripts in [websocket_test.zip](https://github.com/aaugustin/websockets/files/3571125/websocket_test.zip)

I am assuming this is related to issue #551?

For context, this appears to be the cause for rare failures (1 out of ~50 runs) for a test case I have for disconnection, because I check logs for errors and expects connect to return in a short timespan after the connection closed.

**Comment by aaugustin** [comment] 2020-07-26 20:10
This may be resolved in websockets ≥ 8.0 (due to #627). Are you able to check if it still happens?

**Comment by BenjaminHamon** [comment] 2020-07-31 09:31
I just checked. It still happens.
Tested with websockets 8.1 installed with pip, then with a local clone on master, with Python 3.8.1 and on Windows 10.

**Comment by aaugustin** [comment] 2020-07-31 10:43
Thanks for checking. Is the test case a standalone script that you can share?

It will be easier if I can reproduce the bug. Which implies it will be easier if it isn't a Windows-only bug.

**Comment by BenjaminHamon** [comment] 2020-08-02 17:32
The debug scripts are in the original issue, in the zip file.

**Comment by aaugustin** [comment] 2021-06-17 20:08
I can reproduce this.

**Server**

```python
#!/usr/bin/env python

import asyncio
import logging
import time

import websockets

logging.basicConfig(format="%(asctime)s %(message)s", level=logging.DEBUG)

async def test(websocket, path):
    time.sleep(2)

async def main():
    async with websockets.serve(test, "localhost", 8765):
        await asyncio.Future()  # run forever

asyncio.run(main())
```

**Client**

```python
#!/usr/bin/env python

import asyncio
import logging
import time

import websockets

logging.basicConfig(format="%(asctime)s %(message)s", level=logging.DEBUG)

async def test():
    uri = "ws://localhost:8765"
    async with websockets.connect(uri) as websocket:
        time.sleep(1)
        await websocket.ping()
        time.sleep(2)

asyncio.run(test())
```

**Server log**

```
2021-06-17 22:06:44,244 Using selector: KqueueSelector
2021-06-17 22:06:44,289 server listening on [::1]:8765
2021-06-17 22:06:44,289 server listening on 127.0.0.1:8765
2021-06-17 22:06:50,909 = connection is CONNECTING
2021-06-17 22:06:50,910 < GET / HTTP/1.1
2021-06-17 22:06:50,910 < Host: localhost:8765
2021-06-17 22:06:50,910 < Upgrade: websocket
2021-06-17 22:06:50,910 < Connection: Upgrade
2021-06-17 22:06:50,910 < Sec-WebSocket-Key: VnhdXs+tRHa7buz1Md0hfA==
2021-06-17 22:06:50,910 < Sec-WebSocket-Version: 13
2021-06-17 22:06:50,910 < Sec-WebSocket-Extensions: permessage-deflate; server_max_window_bits=12; client_max_window_bits=12
2021-06-17 22:06:50,910 < User-Agent: Python/3.10 websockets/9.1
2021-06-17 22:06:50,911 > HTTP/1.1 101 Switching Protocols
2021-06-17 22:06:50,911 > Upgrade: websocket
2021-06-17 22:06:50,911 > Connection: Upgrade
2021-06-17 22:06:50,911 > Sec-WebSocket-Accept: a9lRwXyxTRvQW0ii/6J6OGh40Cw=
2021-06-17 22:06:50,911 > Sec-WebSocket-Extensions: permessage-deflate; server_max_window_bits=12; client_max_window_bits=12
2021-06-17 22:06:50,911 > Date: Thu, 17 Jun 2021 20:06:50 GMT
2021-06-17 22:06:50,911 > Server: Python/3.10 websockets/9.1
2021-06-17 22:06:50,911 connection open
2021-06-17 22:06:50,911 = connection is OPEN
2021-06-17 22:06:52,916 = connection is CLOSING
2021-06-17 22:06:52,917 > CLOSE 1000 (OK) [2 bytes]
2021-06-17 22:06:52,917 < PING 08 7d b2 4f [binary, 4 bytes]
2021-06-17 22:07:02,918 x half-closing TCP connection
2021-06-17 22:07:02,919 = connection is CLOSED
2021-06-17 22:07:02,919 connection closed
```

**Client log**

```
2021-06-17 22:06:50,881 Using selector: KqueueSelector
2021-06-17 22:06:50,909 = connection is CONNECTING
2021-06-17 22:06:50,909 > GET / HTTP/1.1
2021-06-17 22:06:50,909 > Host: localhost:8765
2021-06-17 22:06:50,909 > Upgrade: websocket
2021-06-17 22:06:50,909 > Connection: Upgrade
2021-06-17 22:06:50,909 > Sec-WebSocket-Key: VnhdXs+tRHa7buz1Md0hfA==
2021-06-17 22:06:50,909 > Sec-WebSocket-Version: 13
2021-06-17 22:06:50,909 > Sec-WebSocket-Extensions: permessage-deflate; server_max_window_bits=12; client_max_window_bits=12
2021-06-17 22:06:50,909 > User-Agent: Python/3.10 websockets/9.1
2021-06-17 22:06:50,912 < HTTP/1.1 101 Switching Protocols
2021-06-17 22:06:50,912 < Upgrade: websocket
2021-06-17 22:06:50,912 < Connection: Upgrade
2021-06-17 22:06:50,912 < Sec-WebSocket-Accept: a9lRwXyxTRvQW0ii/6J6OGh40Cw=
2021-06-17 22:06:50,912 < Sec-WebSocket-Extensions: permessage-deflate; server_max_window_bits=12; client_max_window_bits=12
2021-06-17 22:06:50,912 < Date: Thu, 17 Jun 2021 20:06:50 GMT
2021-06-17 22:06:50,912 < Server: Python/3.10 websockets/9.1
2021-06-17 22:06:50,912 = connection is OPEN
2021-06-17 22:06:51,917 > PING 08 7d b2 4f [binary, 4 bytes]
2021-06-17 22:06:53,921 = connection is CLOSING
2021-06-17 22:06:53,921 > CLOSE 1000 (OK) [2 bytes]
2021-06-17 22:06:53,922 < CLOSE 1000 (OK) [2 bytes]
2021-06-17 22:07:02,918 = connection is CLOSED
2021-06-17 22:07:02,919 Future exception was never retrieved
future: <Future finished exception=ConnectionClosedOK(Close(code=1000, reason=''), Close(code=1000, reason=''), False)>
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)
```

**Closed** 2021-06-17 20:31 UTC
Labels: bug
